//! The three refusals this crate exists to make structural.
//!
//! * **A secret cannot be printed or serialised.** Not "is not, by convention" —
//!   cannot. The redacting `Debug` and `Display` are checked directly, the
//!   serialised form of a credential holding a secret is searched for it, and
//!   so are the error messages and the adapter's own `Debug` output after a
//!   logon. Every one of those is a real path a token has escaped through in a
//!   real system.
//! * **There is no live venue.** [`AdapterClass`] has no `Live` variant, so
//!   nothing deserialises into one and nothing constructs one. The compile-time
//!   half of that claim is a `compile_fail` doctest in the crate root; this is
//!   the half a configuration file could otherwise get past.
//! * **An order cannot reach a venue that is not ready.** The ticket is proof
//!   about a moment, not a flag, and the tests below try every way of holding
//!   one that has stopped being true.
//!
//! The string used to prove redaction is a marker, not a credential: it is
//! generated by this file, means nothing to anything, and is here so that a
//! test asserting "the output does not contain the secret" is not quietly
//! passing because the secret was empty.

#![allow(clippy::panic_in_result_fn)]

use qip_brokers::adapter::{AdapterClass, VenueAdapter, stamp_simulated};
use qip_brokers::connection::{ConnectionPhase, ConnectionState};
use qip_brokers::credential::{
    RequirementKind, Secret, VenueCredential, VenueRequirement, describe_missing,
    requirements_of_kind, standard_requirements,
};
use qip_brokers::exchange::{ExchangeSettings, SimulatedExchange};
use qip_contracts::venue::VenueId;
use qip_core::error::Result;
use qip_core::ids::{FillId, ObjectId, OrderId};
use qip_core::time::{Duration, Timestamp};
use qip_core::{Decimal, dec};
use qip_execution_engine::broker::Broker;
use qip_execution_engine::order::{Fill, Order, OrderType, Side};
use qip_financial::asset_class::InstrumentType;
use qip_financial::object::FinancialObject;
use qip_financial::quality::Provenance;

/// A marker that is not a credential and authenticates nothing.
///
/// Its only job is to be findable. A test that searches output for a secret
/// proves nothing unless the secret was distinctive and actually present, so
/// every assertion below is paired with one showing this string *is* in the
/// credential it claims is not leaking it.
const MARKER: &str = "marker-string-that-must-never-appear-in-output";

const VENUE: &str = "XSIM";
const ACCOUNT: &str = "book-under-test";

fn start() -> Timestamp {
    Timestamp::from_civil(2026, 8, 24)
}

fn venue() -> VenueId {
    VenueId::new(VENUE)
}

fn object() -> ObjectId {
    ObjectId::from_string("OBJ00000000000000000000AAA")
}

fn session_credential_name() -> String {
    standard_requirements(&venue())
        .into_iter()
        .find(|requirement| requirement.kind == RequirementKind::SessionCredential)
        .map(|requirement| requirement.name)
        .expect("the standard list always names a session credential")
}

/// A credential carrying a resolved value, which is the dangerous shape.
fn credential_holding_a_secret() -> VenueCredential {
    let enforced = requirements_of_kind(
        &standard_requirements(&venue()),
        &[RequirementKind::Account, RequirementKind::SessionCredential],
    );
    let mut credential =
        VenueCredential::satisfying(VENUE, ACCOUNT, &enforced).expect("a named venue and account");
    credential = credential.with_secret(
        session_credential_name(),
        format!("QIP_{VENUE}_CREDENTIAL"),
        Secret::new(MARKER),
    );
    credential
}

// --- a secret cannot be printed or serialised -------------------------------

#[test]
fn a_secret_redacts_in_debug_and_display() {
    let secret = Secret::new(MARKER);

    // Non-vacuity first: the value really is in there.
    assert_eq!(secret.expose_str().expect("valid text"), MARKER);
    assert!(!secret.is_empty());

    assert_eq!(format!("{secret:?}"), "Secret(<redacted>)");
    assert_eq!(format!("{secret}"), "<redacted>");
    // Not even the length, which is a hint, or a prefix, which is a head start.
    assert!(!format!("{secret:?}").contains(&MARKER.len().to_string()));
    assert!(!format!("{secret:?}").contains(&MARKER[..8]));
}

#[test]
fn a_secret_inside_a_struct_still_redacts() {
    // A `Debug` derived on a wrapper delegates to the field's `Debug`, which is
    // the path by which a secret usually reaches a log: nobody prints the
    // secret, somebody prints the struct that holds it.
    #[derive(Debug)]
    struct Session {
        account: &'static str,
        secret: Secret,
    }

    let session = Session {
        account: ACCOUNT,
        secret: Secret::new(MARKER),
    };
    let rendered = format!("{session:?}");
    // Non-vacuity: the wrapper really does hold the marker, and its other field
    // really does print.
    assert_eq!(session.secret.expose_str().expect("valid text"), MARKER);
    assert!(
        rendered.contains(session.account),
        "the harmless field should still print: {rendered}"
    );
    assert!(
        !rendered.contains(MARKER),
        "a derived Debug must not defeat the redaction: {rendered}"
    );
}

#[test]
fn a_credential_never_serialises_the_secret_it_carries() -> Result<()> {
    let credential = credential_holding_a_secret();
    let name = session_credential_name();

    // Non-vacuity: the credential really is holding the marker.
    assert_eq!(credential.resolved_count(), 1);
    assert_eq!(
        credential
            .secret(&name)
            .expect("the secret is present")
            .expose_str()?,
        MARKER
    );

    let json = serde_json::to_string(&credential).expect("a credential serialises");
    assert!(
        !json.contains(MARKER),
        "a secret reached a serialised form: {json}"
    );
    // What *should* be there: the reference, which is a configuration note.
    assert!(json.contains(&format!("QIP_{VENUE}_CREDENTIAL")), "{json}");
    assert!(json.contains(ACCOUNT), "{json}");

    assert!(!format!("{credential:?}").contains(MARKER));
    assert!(!format!("{credential}").contains(MARKER));
    assert!(format!("{credential:?}").contains("redacted"));

    // A credential that came off the wire has references and no values: a
    // secret never left over it, so it cannot arrive over it either.
    let restored: VenueCredential = serde_json::from_str(&json).expect("a credential deserialises");
    assert_eq!(restored.resolved_count(), 0);
    assert!(restored.secret(&name).is_none());
    assert_eq!(
        restored.reference(&name),
        Some(format!("QIP_{VENUE}_CREDENTIAL").as_str())
    );
    assert_eq!(restored.account(), ACCOUNT);
    assert_eq!(restored.venue(), VENUE);
    Ok(())
}

#[test]
fn a_refusal_names_the_requirement_and_not_the_value() {
    let credential = credential_holding_a_secret();
    let elsewhere = VenueId::new("XOTHER");

    let error = credential
        .require(&elsewhere, &standard_requirements(&elsewhere))
        .expect_err("a credential is not transferable between venues");
    assert_eq!(error.code(), "denied");
    assert!(!error.message().contains(MARKER), "{}", error.message());
    assert!(!format!("{error}").contains(MARKER));

    let error = credential
        .require(&venue(), &standard_requirements(&venue()))
        .expect_err("the standard list is longer than what a simulator enforces");
    assert_eq!(error.code(), "unavailable");
    assert!(!error.message().contains(MARKER), "{}", error.message());
    assert!(
        error.message().contains("QIP_XSIM_ENDPOINT"),
        "{}",
        error.message()
    );
}

#[test]
fn an_adapter_that_authenticated_with_a_secret_does_not_hold_it() -> Result<()> {
    let mut exchange = SimulatedExchange::new(venue(), ExchangeSettings::orderly(), 41, start());
    exchange.list(instrument());
    exchange.bring_up(&credential_holding_a_secret(), start())?;

    assert_eq!(exchange.account(), Some(ACCOUNT));
    let rendered = format!("{exchange:?}");
    assert!(
        rendered.contains(ACCOUNT),
        "the account is not a secret and should be visible"
    );
    assert!(
        !rendered.contains(MARKER),
        "the adapter kept the secret where a log could find it"
    );

    // The health report is serialised into events and dashboards.
    let health = serde_json::to_string(&exchange.health(start())).expect("health serialises");
    assert!(!health.contains(MARKER), "{health}");
    Ok(())
}

// --- there is no live venue -------------------------------------------------

#[test]
fn no_configuration_deserialises_into_a_live_venue() {
    for refused in [
        "\"live\"",
        "\"production\"",
        "\"real\"",
        "\"Live\"",
        "\"LIVE\"",
    ] {
        assert!(
            serde_json::from_str::<AdapterClass>(refused).is_err(),
            "{refused} must not name a venue class this crate can be"
        );
    }
    assert_eq!(
        serde_json::from_str::<AdapterClass>("\"simulated\"").expect("simulated is a class"),
        AdapterClass::Simulated
    );
    assert_eq!(
        serde_json::from_str::<AdapterClass>("\"sandbox\"").expect("sandbox is a class"),
        AdapterClass::Sandbox
    );
}

#[test]
fn every_class_this_crate_can_be_is_paper() {
    // If a variant is ever added, this fails until somebody states what it is.
    for class in [AdapterClass::Simulated, AdapterClass::Sandbox] {
        assert!(class.is_paper(), "{} is not paper", class.as_str());
        assert_eq!(
            serde_json::to_string(&class).expect("a class serialises"),
            format!("\"{}\"", class.as_str())
        );
    }
}

#[test]
fn every_fill_the_venue_produces_is_marked_simulated() -> Result<()> {
    let mut exchange = SimulatedExchange::new(venue(), ExchangeSettings::orderly(), 42, start());
    exchange.list(instrument());
    exchange.seed_liquidity(
        &object(),
        Side::Sell,
        dec!("100.02"),
        Decimal::from_int(50),
        start(),
    )?;
    exchange.bring_up(&credential_holding_a_secret(), start())?;

    assert_eq!(exchange.class(), AdapterClass::Simulated);
    assert!(exchange.is_simulated());

    let ticket = exchange.ready(start())?;
    let ack = exchange.submit_order(&ticket, &order("marked", Side::Buy, 30), start())?;
    assert!(ack.simulated);
    assert!(!ack.fills.is_empty());
    assert!(ack.fills.iter().all(|fill| fill.simulated));
    assert!(
        exchange
            .query_fills(None)?
            .iter()
            .all(|fill| fill.simulated)
    );
    assert!(
        exchange
            .drain_bookable_fills()
            .iter()
            .all(|bookable| bookable.fill.simulated)
    );
    Ok(())
}

#[test]
fn the_adapter_overwrites_a_fill_that_claims_to_be_real() {
    // A venue message does not get a vote on the single most consequential bit
    // in the execution path.
    let mut forged = vec![Fill {
        fill_id: FillId::from_string("forged"),
        order_id: OrderId::from_string("forged"),
        at: start(),
        quantity: Decimal::from_int(1),
        price: dec!("100"),
        costs: Decimal::ZERO,
        venue: VENUE.to_string(),
        simulated: false,
    }];
    stamp_simulated(&mut forged, true);
    assert!(forged.iter().all(|fill| fill.simulated));
}

// --- an order cannot reach a venue that is not ready ------------------------

#[test]
fn a_session_cannot_skip_a_step() {
    let mut connection = ConnectionState::new(venue(), Duration::from_secs(30), start());
    assert_eq!(connection.phase(), ConnectionPhase::Disconnected);

    // Disconnected is not authenticated, and a socket is not a session.
    assert_eq!(
        connection
            .authenticated(start(), ACCOUNT)
            .expect_err("no transport")
            .code(),
        "invalid"
    );
    assert_eq!(
        connection
            .make_ready(start())
            .expect_err("nothing to promote")
            .code(),
        "invalid"
    );
    assert_eq!(
        connection
            .ready_ticket(start())
            .expect_err("no session")
            .code(),
        "denied"
    );
    assert_eq!(
        connection
            .observe_heartbeat(start())
            .expect_err("no session")
            .code(),
        "denied"
    );

    connection
        .connect(start())
        .expect("a transport may always be opened from disconnected");
    assert_eq!(
        connection
            .make_ready(start())
            .expect_err("a socket is not a logon")
            .code(),
        "invalid"
    );

    connection
        .authenticated(start(), ACCOUNT)
        .expect("logon after connect");
    let error = connection
        .make_ready(start())
        .expect_err("a session nobody has heard from is not a session that works");
    assert_eq!(error.code(), "invalid");
    assert!(error.message().contains("heartbeat"), "{}", error.message());

    connection
        .observe_heartbeat(start())
        .expect("the venue answers");
    assert_eq!(connection.phase(), ConnectionPhase::Ready);
    assert!(connection.ready_ticket(start()).is_ok());
}

#[test]
fn a_ticket_is_proof_about_a_moment_and_not_a_flag() {
    let mut connection = ConnectionState::new(venue(), Duration::from_secs(30), start());
    connection.connect(start()).expect("connect");
    connection.authenticated(start(), ACCOUNT).expect("logon");
    connection.observe_heartbeat(start()).expect("heartbeat");
    let ticket = connection.ready_ticket(start()).expect("ready");

    // The same ticket, later, after the venue has gone quiet.
    let later = start().saturating_add(Duration::from_secs(90));
    let error = connection
        .authorise(&ticket, later)
        .expect_err("the moment has passed");
    assert_eq!(error.code(), "denied");
    assert!(error.message().contains("degraded"), "{}", error.message());

    // The same ticket, after the session was rebuilt underneath it.
    connection.disconnect(start(), "rebuilding");
    connection.connect(start()).expect("connect");
    connection.authenticated(start(), ACCOUNT).expect("logon");
    connection.observe_heartbeat(start()).expect("heartbeat");
    let error = connection
        .authorise(&ticket, start())
        .expect_err("a new session is not the old one");
    assert_eq!(error.code(), "denied");
    assert!(error.message().contains("session"), "{}", error.message());
}

#[test]
fn a_ticket_for_one_venue_authorises_nothing_at_another() {
    let mut here = ConnectionState::new(venue(), Duration::from_secs(30), start());
    here.connect(start()).expect("connect");
    here.authenticated(start(), ACCOUNT).expect("logon");
    here.observe_heartbeat(start()).expect("heartbeat");
    let ticket = here.ready_ticket(start()).expect("ready");
    assert_eq!(ticket.venue(), VENUE);
    assert_eq!(ticket.issued_at(), start());

    let mut elsewhere =
        ConnectionState::new(VenueId::new("XOTHER"), Duration::from_secs(30), start());
    elsewhere.connect(start()).expect("connect");
    elsewhere.authenticated(start(), ACCOUNT).expect("logon");
    elsewhere.observe_heartbeat(start()).expect("heartbeat");

    let error = elsewhere
        .authorise(&ticket, start())
        .expect_err("tickets are not transferable");
    assert_eq!(error.code(), "denied");
}

#[test]
fn a_session_that_goes_quiet_is_degraded_whether_or_not_anybody_looks() {
    let mut connection = ConnectionState::new(venue(), Duration::from_secs(30), start());
    connection.connect(start()).expect("connect");
    connection.authenticated(start(), ACCOUNT).expect("logon");
    connection.observe_heartbeat(start()).expect("heartbeat");

    let later = start().saturating_add(Duration::from_secs(31));
    // Pure: reporting a stale `ready` because nobody happened to call a
    // mutating method is the exact failure this crate exists to avoid.
    assert_eq!(connection.phase(), ConnectionPhase::Ready);
    assert_eq!(connection.effective_phase(later), ConnectionPhase::Degraded);
    assert!(connection.heartbeat_overdue(later));
    assert_eq!(
        connection.heartbeat_gap(later),
        Some(Duration::from_secs(31))
    );

    assert_eq!(connection.observe(later), ConnectionPhase::Degraded);
    assert_eq!(connection.phase(), ConnectionPhase::Degraded);
    // A cancel still has a session to travel on.
    assert!(connection.require_session(later).is_ok());
    // Observing twice must not try an illegal transition.
    assert_eq!(connection.observe(later), ConnectionPhase::Degraded);
    assert!(connection.transitions().len() >= 4);
}

// --- credentials refuse rather than default ---------------------------------

#[test]
fn a_credential_has_no_default_venue_and_no_default_account() {
    assert_eq!(
        VenueCredential::new("  ", ACCOUNT)
            .expect_err("blank venue")
            .code(),
        "invalid"
    );
    let error = VenueCredential::new(VENUE, "   ").expect_err("blank account");
    assert_eq!(error.code(), "invalid");
    assert!(
        error.message().contains("no default account"),
        "{}",
        error.message()
    );
}

#[test]
fn an_incomplete_credential_is_refused_with_the_list_of_what_is_missing() -> Result<()> {
    let requirements = standard_requirements(&venue());
    let empty = VenueCredential::new(VENUE, ACCOUNT)?;
    assert!(empty.is_empty());
    assert_eq!(empty.missing(&requirements).len(), requirements.len());

    let error = empty
        .require(&venue(), &requirements)
        .expect_err("nothing is satisfied");
    assert_eq!(error.code(), "unavailable");
    for requirement in &requirements {
        assert!(
            error.message().contains(&requirement.env_var),
            "the refusal must name {}: {}",
            requirement.env_var,
            error.message()
        );
    }

    // The same sentence, reached directly.
    assert_eq!(
        describe_missing(&venue(), &requirements),
        error.message(),
        "one refusal, worded once"
    );
    assert_eq!(
        describe_missing(&venue(), &[]),
        "XSIM needs nothing further"
    );
    Ok(())
}

#[test]
fn a_simulator_enforces_only_what_it_can_honestly_check() -> Result<()> {
    let requirements = standard_requirements(&venue());
    // Six items, of which a simulator can genuinely check two: it cannot dial
    // an endpoint it does not have or verify an entitlement nobody granted.
    assert_eq!(requirements.len(), 6);
    let enforceable = requirements_of_kind(
        &requirements,
        &[RequirementKind::Account, RequirementKind::SessionCredential],
    );
    assert_eq!(enforceable.len(), 2);

    let credential = VenueCredential::satisfying(VENUE, ACCOUNT, &enforceable)?;
    credential.require(&venue(), &enforceable)?;
    // And it still reports itself incomplete as a venue.
    assert_eq!(credential.missing(&requirements).len(), 4);

    let mut exchange = SimulatedExchange::new(venue(), ExchangeSettings::orderly(), 43, start());
    exchange.list(instrument());
    assert_eq!(exchange.missing_requirements().len(), 6);
    exchange.bring_up(&credential, start())?;
    assert_eq!(
        exchange.missing_requirements().len(),
        6,
        "a logon does not complete a venue"
    );
    Ok(())
}

#[test]
fn requirements_say_which_ones_a_deployment_can_satisfy_by_itself() {
    let requirements = standard_requirements(&venue());
    let self_service: Vec<&VenueRequirement> = requirements
        .iter()
        .filter(|requirement| requirement.kind.is_self_service())
        .collect();
    // An endpoint and a protocol parameter are configuration changes; an
    // entitlement needs somebody at the venue to act, and that is days.
    assert_eq!(self_service.len(), 2);
    assert!(!RequirementKind::Entitlement.is_self_service());
    assert!(!RequirementKind::SessionCredential.is_self_service());

    for requirement in &requirements {
        let described = requirement.describe();
        assert!(described.contains(&requirement.env_var), "{described}");
        assert!(described.contains(requirement.kind.as_str()), "{described}");
        // The same requirement, in the vocabulary the routing gateways use, so
        // the two frameworks cannot disagree about what a venue is missing.
        let gateway = requirement.as_gateway_credential();
        assert_eq!(gateway.env_var, requirement.env_var);
        assert_eq!(gateway.purpose, requirement.purpose);
    }
}

#[test]
fn authentication_refuses_a_credential_for_another_venue() -> Result<()> {
    let mut exchange = SimulatedExchange::new(venue(), ExchangeSettings::orderly(), 44, start());
    exchange.list(instrument());
    let elsewhere = VenueId::new("XOTHER");
    let enforceable = requirements_of_kind(
        &standard_requirements(&elsewhere),
        &[RequirementKind::Account, RequirementKind::SessionCredential],
    );
    let wrong = VenueCredential::satisfying("XOTHER", ACCOUNT, &enforceable)?;

    let error = exchange
        .bring_up(&wrong, start())
        .expect_err("not this venue's credential");
    assert_eq!(error.code(), "denied");
    assert_eq!(
        exchange.account(),
        None,
        "a refused logon must not name an account"
    );
    assert!(exchange.ready(start()).is_err());
    Ok(())
}

// --- shared fixtures --------------------------------------------------------

fn instrument() -> FinancialObject {
    FinancialObject::builder(object(), "AAA", InstrumentType::CommonStock)
        .name("Instrument A")
        .venue(VENUE)
        .price(dec!("100"))
        .lot_size(Decimal::ONE)
        .tick_size(dec!("0.01"))
        .provenance(Provenance::synthetic("qip-brokers test", start()))
        .build(start())
        .expect("a structurally valid instrument")
}

fn order(label: &str, side: Side, quantity: i64) -> Order {
    Order::new(
        OrderId::from_string(label),
        object(),
        side,
        Decimal::from_int(quantity),
        OrderType::Limit {
            price: dec!("100.02"),
        },
        dec!("100"),
        "proposal-under-test",
        vec!["hypothesis-under-test".to_string()],
        "scope-under-test",
        start(),
    )
}
