//! The six controls composed, and the report that makes "compliant" checkable.
//!
//! A [`ComplianceReport`] is generated by iterating [`Control::all`], so a
//! control cannot be omitted by forgetting to mention it — adding a seventh
//! control to the contract makes this crate fail to compile until the seventh
//! arm is written. That is deliberate: the failure mode of a governance plane
//! is not a broken control, it is a control nobody noticed was never wired in.
//!
//! `enforced` is computed, not asserted. Most controls are enforced by the
//! shape of their types and are therefore unconditionally true; the artifact
//! control is the exception, because a store whose contents no longer verify
//! is a control that has stopped working, and the report says so.

use crate::approval::ApprovalChain;
use crate::artifacts::ArtifactStore;
use crate::incident::{IncidentLog, ResponsePolicy};
use crate::licensing::EntitlementRegistry;
use crate::model_risk::ModelRiskRegister;
use crate::pit::{LeakageDetector, PointInTime};
use crate::signing::SigningKey;
use qip_contracts::governance::Control;
use qip_contracts::time::Stamped;
use qip_core::error::{Error, Result};
use qip_core::{Decimal, Timestamp};
use serde::{Deserialize, Serialize};

/// Whether one control is enforced, and by what.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct ControlStatus {
    pub control: Control,
    /// Whether the mechanism is in place and working right now.
    pub enforced: bool,
    /// The specific thing that makes the unsafe action impossible or refused.
    /// A sentence naming a type or a function, never "policy requires that…".
    ///
    /// Owned rather than borrowed so a report round-trips through storage: an
    /// audit record that cannot be read back is not a record.
    pub mechanism: String,
    /// What the plane currently holds under this control.
    pub evidence: Vec<String>,
    /// Honest gaps. A caveat is not a failure, but a control described without
    /// its caveats is worse than one labelled advisory.
    pub caveats: Vec<String>,
}

/// The state of all six controls at a moment.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct ComplianceReport {
    generated_at: Timestamp,
    statuses: Vec<ControlStatus>,
}

impl ComplianceReport {
    pub fn generated_at(&self) -> Timestamp {
        self.generated_at
    }

    pub fn statuses(&self) -> &[ControlStatus] {
        &self.statuses
    }

    pub fn status(&self, control: Control) -> Option<&ControlStatus> {
        self.statuses.iter().find(|s| s.control == control)
    }

    /// Controls that are named but not currently enforced.
    pub fn unenforced(&self) -> Vec<Control> {
        self.statuses
            .iter()
            .filter(|s| !s.enforced)
            .map(|s| s.control)
            .collect()
    }

    /// Every caveat across every control, for a reviewer who wants the honest
    /// list rather than the headline.
    pub fn caveats(&self) -> Vec<(Control, &str)> {
        self.statuses
            .iter()
            .flat_map(|s| s.caveats.iter().map(move |c| (s.control, c.as_str())))
            .collect()
    }

    pub fn is_fully_enforced(&self) -> bool {
        self.statuses.len() == Control::all().len() && self.statuses.iter().all(|s| s.enforced)
    }

    /// Fail loudly if any control is missing or not enforced.
    ///
    /// Intended for a deployment's start-up check: a platform that cannot
    /// prove its governance plane is wired should not begin trading.
    pub fn require_fully_enforced(&self) -> Result<()> {
        let missing: Vec<&str> = Control::all()
            .into_iter()
            .filter(|c| self.status(*c).is_none())
            .map(|c| c.as_str())
            .collect();
        if !missing.is_empty() {
            return Err(Error::guard(format!(
                "the compliance report covers no mechanism for: {}",
                missing.join(", ")
            )));
        }
        let unenforced: Vec<&str> = self
            .statuses
            .iter()
            .filter(|s| !s.enforced)
            .map(|s| s.control.as_str())
            .collect();
        if !unenforced.is_empty() {
            return Err(Error::guard(format!(
                "these controls are not enforced right now: {}",
                unenforced.join(", ")
            )));
        }
        Ok(())
    }
}

/// The six controls, composed.
///
/// Holding one of these is holding the governance plane. Subsystems are handed
/// the pieces they need — a strategy gets a [`PointInTime`] reader, a model
/// gets the risk register, an edge cell gets an approved envelope — and none
/// of them can construct the privileged values themselves.
#[derive(Debug)]
pub struct CompliancePlane {
    entitlements: EntitlementRegistry,
    model_risk: ModelRiskRegister,
    approvals: ApprovalChain,
    artifacts: ArtifactStore,
    incidents: IncidentLog,
}

impl CompliancePlane {
    /// Wire the plane.
    ///
    /// The signing key is shared by the capital and artifact controls on
    /// purpose: they are the same trust root, and a deployment that rotated
    /// one and not the other would have a provenance chain that verified
    /// against a key no longer authorising capital.
    pub fn new(
        key: SigningKey,
        dual_approval_threshold: Decimal,
        policy: ResponsePolicy,
    ) -> Result<Self> {
        Ok(Self {
            entitlements: EntitlementRegistry::new(),
            model_risk: ModelRiskRegister::new(),
            approvals: ApprovalChain::new(dual_approval_threshold, key.clone())?,
            artifacts: ArtifactStore::new(key),
            incidents: IncidentLog::new(policy),
        })
    }

    /// A point-in-time reader over some facts. Control 1's entry point.
    ///
    /// A method on the plane rather than a free function so that every read in
    /// the platform is reachable from the governance object, and an audit can
    /// find them by looking at who holds a plane.
    pub fn reader<T>(
        &self,
        as_of: Timestamp,
        facts: impl IntoIterator<Item = Stamped<T>>,
    ) -> PointInTime<T> {
        PointInTime::as_of(as_of, facts)
    }

    /// A detector for inputs that did not come through a reader.
    pub fn leakage_detector(&self, as_of: Timestamp) -> LeakageDetector {
        LeakageDetector::new(as_of)
    }

    pub fn entitlements(&self) -> &EntitlementRegistry {
        &self.entitlements
    }

    pub fn entitlements_mut(&mut self) -> &mut EntitlementRegistry {
        &mut self.entitlements
    }

    pub fn model_risk(&self) -> &ModelRiskRegister {
        &self.model_risk
    }

    pub fn model_risk_mut(&mut self) -> &mut ModelRiskRegister {
        &mut self.model_risk
    }

    pub fn approvals(&self) -> &ApprovalChain {
        &self.approvals
    }

    pub fn approvals_mut(&mut self) -> &mut ApprovalChain {
        &mut self.approvals
    }

    pub fn artifacts(&self) -> &ArtifactStore {
        &self.artifacts
    }

    pub fn artifacts_mut(&mut self) -> &mut ArtifactStore {
        &mut self.artifacts
    }

    pub fn incidents(&self) -> &IncidentLog {
        &self.incidents
    }

    pub fn incidents_mut(&mut self) -> &mut IncidentLog {
        &mut self.incidents
    }

    /// Whether a strategy on a cell may act at all right now.
    ///
    /// The one cross-control question every subsystem asks. It consults the
    /// incident log rather than a cached flag, so clearing a halt takes effect
    /// everywhere at once.
    pub fn may_act(&self, scope: &str, cell: &str) -> bool {
        !self.incidents.is_halted(scope, cell)
    }

    /// Enumerate all six controls and what enforces each.
    ///
    /// Built from [`Control::all`], so the report is exhaustive by
    /// construction rather than by the author remembering.
    pub fn report(&self, now: Timestamp) -> ComplianceReport {
        let statuses = Control::all()
            .into_iter()
            .map(|control| self.status_of(control, now))
            .collect();
        ComplianceReport {
            generated_at: now,
            statuses,
        }
    }

    fn status_of(&self, control: Control, now: Timestamp) -> ControlStatus {
        match control {
            Control::BitemporalTruth => ControlStatus {
                control,
                enforced: true,
                mechanism: "crate::pit::PointInTime discards facts whose known-time is after the \
                            as-of at construction, so no accessor can return one; restrict_to \
                            only narrows the horizon, and LeakageDetector names inputs that \
                            arrived from outside a reader".to_string(),
                evidence: vec![
                    "readers are built per read and hold no future facts".to_string(),
                    "widening a reader is refused rather than silently permitted".to_string(),
                ],
                caveats: vec![
                    "a value stripped of its Stamped wrapper before it reaches a reader is \
                     outside this control; keep facts stamped to the point of use"
                        .to_string(),
                ],
            },
            Control::LicensingAndEntitlements => {
                let refusals = self.entitlements.refusals().len();
                ControlStatus {
                    control,
                    enforced: true,
                    mechanism: "crate::licensing::LicensedData holds its value privately and \
                                every accessor takes a Usage and the registry, recording the \
                                decision; derive() carries the originating dataset onto the \
                                derived value so a licence cannot be laundered by a map".to_string(),
                    evidence: vec![
                        format!("{} entitlements registered", self.entitlements.len()),
                        format!("{refusals} refusals recorded"),
                        "a dataset with no recorded entitlement is treated as unlicensed"
                            .to_string(),
                    ],
                    caveats: vec![
                        "expiry is checked against the timestamp the caller passes; the plane \
                         reads no ambient clock, so a caller passing a stale `now` weakens this"
                            .to_string(),
                    ],
                }
            }
            Control::ModelRiskAndExplainability => {
                let overdue: Vec<String> = self
                    .model_risk
                    .overdue(now)
                    .into_iter()
                    .map(|f| f.model_reference().to_string())
                    .collect();
                let mut caveats = vec![
                    "reconciliation proves the attribution sums to the output, not that the \
                     attribution method is the right one"
                        .to_string(),
                ];
                if !overdue.is_empty() {
                    caveats.push(format!(
                        "risk files overdue for review and therefore blocking use: {}",
                        overdue.join(", ")
                    ));
                }
                ControlStatus {
                    control,
                    enforced: true,
                    mechanism: "crate::model_risk::AdmittedOutput has no public constructor; \
                                ModelRiskRegister::admit is the only source and requires the \
                                qip-ai eligibility check, a current risk file, an in-boundary \
                                operating point and an Explanation, which cannot exist unless \
                                its contributions reconcile exactly to the output".to_string(),
                    evidence: vec![
                        format!("{} risk files on record", self.model_risk.len()),
                        format!("{} admission decisions recorded", self.model_risk.admissions().len()),
                        format!("{} overdue at {now}", overdue.len()),
                    ],
                    caveats,
                }
            }
            Control::HumanCapitalApproval => ControlStatus {
                control,
                enforced: true,
                mechanism: "crate::approval::ApprovedCapital has no public constructor and does \
                            not deserialise; ApprovalChain::grant requires an Approval naming a \
                            human who is not the requester, a fresh credential per approver, and \
                            two different approvers above the threshold".to_string(),
                evidence: vec![
                    format!(
                        "dual approval required above {}",
                        self.approvals.dual_threshold()
                    ),
                    format!(
                        "credentials must be under {:?} old",
                        self.approvals.maximum_credential_age()
                    ),
                    format!("{} grants recorded", self.approvals.grants().len()),
                    format!("{} attempts refused", self.approvals.refusals().len()),
                ],
                caveats: vec![
                    "qip_contracts::CapitalEnvelope::new stays public, so an unapproved envelope \
                     can be constructed elsewhere; it cannot become an ApprovedCapital, so \
                     components must take ApprovedCapital rather than CapitalEnvelope"
                        .to_string(),
                ],
            },
            Control::SignedArtifactsAndProvenance => {
                let failures = self.artifacts.integrity_failures();
                let mut caveats = vec![
                    "signing is HMAC-SHA256 over a shared secret: it proves possession of the \
                     key, not the identity of the signer. Production needs asymmetric signing \
                     (Ed25519 or ECDSA P-256) with the private key in a KMS, a certificate \
                     chain binding key to signer, rotation and revocation, and independent \
                     timestamping — see crate::signing"
                        .to_string(),
                ];
                if !failures.is_empty() {
                    caveats.push(format!(
                        "{} stored artifacts no longer verify: {}",
                        failures.len(),
                        failures.join(", ")
                    ));
                }
                ControlStatus {
                    control,
                    // The one status that is genuinely conditional: a store
                    // holding artifacts that no longer verify is a control
                    // that has stopped working, whatever its shape.
                    enforced: failures.is_empty(),
                    mechanism: "crate::artifacts::ArtifactStore::store admits nothing whose bytes \
                                do not hash to its Provenance digest and whose signature does not \
                                verify under the injected key; ProvenanceChain walks inputs back \
                                to registered raw datasets and names the exact digest where it \
                                cannot continue".to_string(),
                    evidence: vec![
                        format!("signing key {}", self.artifacts.key_id()),
                        format!("{} artifacts stored", self.artifacts.len()),
                        format!(
                            "{} raw datasets registered as origins",
                            self.artifacts.raw_datasets().count()
                        ),
                        format!("{} submissions rejected", self.artifacts.rejections().len()),
                    ],
                    caveats,
                }
            }
            Control::KillSwitchAndIncidentResponse => ControlStatus {
                control,
                enforced: true,
                mechanism: "crate::incident::IncidentLog::record needs no authority and applies \
                            ResponsePolicy, which maps Severity to a HaltScope that must name \
                            what it stops; clear_* refuse a stale credential and write a \
                            Clearance naming the operator, the method and the reason".to_string(),
                evidence: vec![
                    format!("response floor {}", self.incidents.policy().floor().as_str()),
                    format!("{} incidents recorded", self.incidents.incidents().len()),
                    format!(
                        "globally halted: {}",
                        self.incidents.is_globally_halted()
                    ),
                    format!(
                        "{} scopes and {} cells halted",
                        self.incidents.halted_scopes().len(),
                        self.incidents.halted_cells().len()
                    ),
                    format!("{} clearances recorded", self.incidents.clearances().len()),
                ],
                caveats: vec![
                    "the halt state lives in this process; a distributed deployment needs the \
                     same record replicated, and an edge cell that cannot reach it must fail \
                     closed on its own capital envelope's expiry"
                        .to_string(),
                ],
            },
        }
    }
}
