"use client";

import { request } from "@/lib/api/client";
import { useResource, type Resource } from "./useResource";

/**
 * The two surfaces on which the platform reports a control it applied to
 * itself, and the two-signature path back from each.
 *
 * `GET /risk/recalibrations` (ADR 0061) is what the LEARN stage proposed
 * about its own risk rules from counterfactual regret, and
 * `GET /venues/withdrawals` (ADR 0062) is which venues it stopped using on
 * its own feasibility evidence. They are one module because they are one
 * kind of fact — the platform narrowing or widening itself, on evidence it
 * recorded, recoverable only by two people signing — and because a reviewer
 * of that surface should see every request this console can make against it
 * in one place and see that each is a GET.
 *
 * **There is no signature here, and there is no fetcher that could make one.**
 * Both signature routes are `POST`, both require an operator, and the gateway
 * refuses any write `@/lib/api/endpoints` does not declare before the
 * deployment credential is read. What this console does instead is render the
 * path and the refusal the platform itself returned for this caller, so the
 * person reading the list learns at that moment that the call cannot succeed
 * from here rather than discovering it mid-recovery.
 *
 * Nothing in this file computes a bound, a share, a delta or a verdict. Every
 * number on the two pages is a field one of these routes answered; the
 * arithmetic that produced it was the platform's, is on the event log, and a
 * second copy of it in a browser would be a second risk model that could
 * disagree with the one that acted.
 */

const POLL_MS = 30_000;

/** A `qip_core::Decimal`, serialised as its exact decimal string. Never parsed here. */
export type DecimalString = string;

/** A `qip_core::Timestamp`, serialised as RFC 3339. Rendered, never recomputed. */
export type Rfc3339 = string;

/**
 * A `qip_twin::Simulated<Decimal>`: a figure computed about a world that did
 * not happen. The wrapper is on the wire — `simulated: true` beside the value
 * — precisely so a reporting surface cannot print it as though it were money
 * that moved, and this console renders the flag beside the figure for the
 * same reason.
 */
export interface SimulatedDecimal {
  readonly simulated_value: DecimalString;
  readonly simulated: boolean;
}

// --- GET /risk/recalibrations ------------------------------------------------------

/**
 * The regret behind a proposal: how many refusals were scored, how many the
 * counterfactual said were wrong, and what standing aside cost in simulation.
 *
 * `window` is a Rust tuple and arrives as a two-element array, oldest first.
 */
export interface RegretEvidence {
  readonly sample: number;
  readonly regrets: number;
  readonly regret_fraction: number;
  readonly would_have_earned: SimulatedDecimal;
  readonly window: readonly [Rfc3339, Rfc3339];
  readonly newest: string;
  readonly scored_orders: readonly string[];
}

/**
 * One proposal to loosen one rule's bound.
 *
 * `rationale` is generated by the platform from the evidence and can be
 * supplied by nobody, so it is rendered as prose the platform wrote rather
 * than as a field a caller filled in. `current_bound` and `proposed_bound`
 * are the `f64` lane the limit kinds already use; they are rendered as they
 * arrived and never differenced here — see the module note.
 */
export interface RecalibrationProposal {
  readonly rule: string;
  /** The limit's kind label, so the record says what sort of bound moved. */
  readonly kind: string;
  readonly current_bound: number;
  readonly proposed_bound: number;
  readonly evidence: RegretEvidence;
  readonly rationale: string;
  /** One of [`PROPOSAL_OUTCOMES`]; an unknown value is rendered as it came. */
  readonly outcome: string;
  readonly at: Rfc3339;
}

export interface Recalibrations {
  /** The limit set this process runs under, by name. */
  readonly limits: string;
  /** Proposals standing open, oldest rule first. */
  readonly open: readonly RecalibrationProposal[];
  /** Every proposal record the log holds, oldest first. */
  readonly history: readonly RecalibrationProposal[];
}

/** The outcomes `qip_kernel::rule_review` writes. Transcribed from its constants. */
export const PROPOSAL_PROPOSED = "proposed";
export const PROPOSAL_WITHDRAWN = "withdrawn";
export const PROPOSAL_ENACTED = "enacted";
export const PROPOSAL_OUTCOMES = [PROPOSAL_PROPOSED, PROPOSAL_WITHDRAWN, PROPOSAL_ENACTED] as const;

// --- GET /venues/withdrawals -------------------------------------------------------

/** Which plane refused: the desk's own order manager, or a regional cell. */
export type FeasibilitySeam = "desk" | "edge";

/**
 * The withdrawal record, with the arithmetic the review made it on. `share`
 * is `count` over `sample` as the platform computed it; this console renders
 * that figure and does not divide.
 */
export interface VenueWithdrawal {
  readonly venue: string;
  readonly constraint: string;
  readonly sample: number;
  readonly count: number;
  readonly share: number;
  readonly seams: readonly FeasibilitySeam[];
  readonly cycle: number;
  readonly at: Rfc3339;
}

export interface WithdrawnVenueRow {
  readonly venue: string;
  /**
   * `null` only where the log no longer holds the record the withdrawn set
   * was resumed from. That is a fact about retention and is rendered as one;
   * it is not "withdrawn for no reason".
   */
  readonly withdrawal: VenueWithdrawal | null;
  /**
   * Whether a first signature is standing. A boolean and not a name: who
   * signed is on the event log, at an authority this list is not served at.
   */
  readonly awaiting_countersignature: boolean;
}

export interface WithdrawnVenues {
  readonly withdrawn: readonly WithdrawnVenueRow[];
  /** Withdrawal records in the log in all, including venues since put back. */
  readonly withdrawals_recorded: number;
  /** The path a signature is posted to, as the platform composes it. */
  readonly reinstatement_path: string;
  /**
   * Why a signature posted to that path would be refused for the credential
   * this deployment holds, or `null` if it would be taken. The platform's own
   * answer, obtained by making the call the signature route makes — not this
   * console's guess about it.
   */
  readonly reinstatement_refusal: string | null;
}

// --- fetchers ----------------------------------------------------------------------

/** The two reads, and the only two. Both GET; see the module note. */
export const selfCorrection = {
  recalibrations: (signal?: AbortSignal) =>
    request<Recalibrations>("/risk/recalibrations", signal ? { signal } : {}),
  venueWithdrawals: (signal?: AbortSignal) =>
    request<WithdrawnVenues>("/venues/withdrawals", signal ? { signal } : {}),
} as const;

export function useRecalibrations(): Resource<Recalibrations> {
  return useResource<Recalibrations>(selfCorrection.recalibrations, {
    key: "risk-recalibrations",
    label: "GET /risk/recalibrations",
    intervalMs: POLL_MS,
  });
}

export function useVenueWithdrawals(): Resource<WithdrawnVenues> {
  return useResource<WithdrawnVenues>(selfCorrection.venueWithdrawals, {
    key: "venue-withdrawals",
    label: "GET /venues/withdrawals",
    intervalMs: POLL_MS,
  });
}

// --- rendering helpers the pages share ------------------------------------------------

/**
 * A bound as the platform sent it.
 *
 * Deliberately not `formatDecimal`, and deliberately not rounded: these
 * arrive as JSON numbers in the `f64` lane the limit kinds use, and
 * `String(value)` is the shortest text that reads back as the same double.
 * A bound displayed to two places would tell an operator a limit sits
 * somewhere it does not.
 */
export function formatBound(value: number | null | undefined): string {
  if (value === null || value === undefined || !Number.isFinite(value)) return "—";
  return String(value);
}
