# What a deployment has to hand to somebody else, and what it has to check.
#
# Each value is null or empty when its half is disabled, so a caller rendering
# these gets the honest picture rather than a plausible-looking endpoint for a
# circuit nobody ordered — the same rule `modules/data` follows.

output "pairing_keys" {
  description = <<-EOT
    Attachment name to the pairing key the partner needs.

    This is the one value in this module that has to leave it: the partner
    cannot provision the far half of the circuit without it, and it is
    generated by Google rather than chosen here.

    Marked sensitive because it is a bearer token in everything but name.
    Whoever holds it can attach a circuit of theirs to a VLAN attachment of
    this project's, so it belongs in the channel the partner ordering process
    uses and not in a CI log. Read it deliberately with
    `terraform output -json pairing_keys`.
  EOT

  value = {
    for name, attachment in google_compute_interconnect_attachment.partner :
    name => attachment.pairing_key
  }

  sensitive = true
}

output "interconnect_attachments" {
  description = <<-EOT
    Attachment name to its region, edge availability domain and state.

    `state` is the field to read before believing any of this works.
    `PENDING_PARTNER` means Google is waiting for the partner; `ACTIVE` means a
    circuit exists and, if `admin_enabled` is true, is carrying routes.
  EOT

  value = {
    for name, attachment in google_compute_interconnect_attachment.partner :
    name => {
      region                   = attachment.region
      edge_availability_domain = attachment.edge_availability_domain
      admin_enabled            = attachment.admin_enabled
      state                    = attachment.state
      cloud_router_ip          = attachment.cloud_router_ip_address
    }
  }
}

output "cloud_routers" {
  description = "Region to the Cloud Router created for it, or empty when partner interconnect is off."
  value = {
    for region, router in google_compute_router.interconnect : region => router.name
  }
}

output "google_apis_endpoint" {
  description = "The Private Service Connect address for Google APIs, or null when it is not enabled."
  value       = var.enable_private_service_connect ? google_compute_global_address.google_apis[0].address : null
}

# The gap, as data. The infrastructure counterpart of the data module's
# `enabled_without_an_adapter`: an operator reads this at plan time instead of
# discovering at cutover that the private path was never finished.
output "still_needs_arranging_out_of_band" {
  description = "What exists here that a circuit, a partner or a DNS change elsewhere must still complete."
  value = compact([
    length(local.attachments) > 0 ? "partner interconnect: each attachment needs a partner circuit ordered against its pairing key, and stays PENDING_PARTNER until the partner provisions their half" : "",
    length([for a in values(local.attachments) : a if !a.admin_enabled]) > 0 ? "partner interconnect: attachments created with admin_enabled = false carry no traffic until somebody enables them after reviewing the far end" : "",
    var.enable_private_service_connect ? "private service connect: the endpoint answers only for traffic already directed at it, so the far end's resolver must map the Google API hostnames to ${var.private_service_connect_address}" : "",
  ])
}
