"use client";

import { Chip, Freshness, StatusChip } from "@/components/data/Bits";
import { Kpi, KpiRow } from "@/components/data/Kpi";
import { Panel, PanelBody, PanelHead, TableWell } from "@/components/data/Panel";
import { EmptyBlock, ResourceView } from "@/components/data/States";
import { platform } from "@/lib/api/client";
import type { SystemStatus } from "@/lib/api/types";
import { formatCount, formatDecimal, formatPercent, formatTimestamp, truncate } from "@/lib/format";
import { useResource } from "@/lib/hooks/useResource";
import {
  formatBound,
  useRecalibrations,
  PROPOSAL_ENACTED,
  PROPOSAL_PROPOSED,
  PROPOSAL_WITHDRAWN,
  type RecalibrationProposal,
} from "@/lib/hooks/useSelfCorrection";

/**
 * Rule recalibrations: what the platform proposed about its own risk limits,
 * on regret it scored itself, and what a signature on one would actually do.
 *
 * `GET /risk/recalibrations` (ADR 0061) answers the limit set this process
 * runs under, the proposals standing open, and every proposal record the log
 * holds. This page renders those three and nothing derived from them. In
 * particular it does **not** subtract one bound from the other, express the
 * move as a percentage, or rank proposals by how much regret they carry:
 * each of those is a risk judgement, the platform has already made the only
 * one that mattered — that this rule refused too much on this evidence — and
 * a second judgement computed in a browser is a second risk model that can
 * disagree with the one that acted.
 *
 * **Two facts this page exists to put on a screen**, because both have been
 * misread from a bare list before they were written down:
 *
 * * An *enacted* proposal did not change this process. The second signature
 *   emits a limit set with one bound replaced, as an artefact for a
 *   deployment to commit and mount; the process that served the request keeps
 *   the limits it booted with. A console that showed `enacted` next to a new
 *   bound would tell an operator a control had moved when it had not.
 * * `would_have_earned` is simulated. It is what the refused paths would have
 *   made in a world that did not happen, and it arrives wrapped in
 *   `Simulated` for exactly that reason. It is rendered with the flag beside
 *   it and never summed into anything the ledger holds.
 *
 * There is no control on this page. Signing is `POST
 * /risk/recalibrations/{rule}/approvals`, it needs an operator, and the
 * gateway refuses any write this console does not declare — so the path is
 * named here as a fact and offered as nothing.
 */
export default function RecalibrationsPage() {
  const recalibrations = useRecalibrations();
  const status = useResource<SystemStatus>(platform.systemStatus, {
    key: "recalibrations-status",
    label: "GET /system/status",
    intervalMs: 15_000,
  });

  return (
    <div className="flex flex-col gap-3 p-3" data-testid="recalibrations-page">
      <Panel>
        <PanelHead
          title="Rule recalibrations"
          meta={<Freshness resource={recalibrations} name="recalibrations" />}
          actions={
            status.data === null ? null : (
              <StatusChip
                tone={status.data.live_capable ? "bad" : "ok"}
                label={status.data.live_capable ? "LIVE-CAPABLE" : "PAPER TRADING"}
                title="GET /system/status: live_capable"
              />
            )
          }
        />
        <PanelBody>
          <p
            className="text-[11.5px] leading-relaxed text-[color:var(--color-ink-dim)]"
            data-testid="recalibrations-declaration"
          >
            <span className="chip mr-2" data-tone="ok" data-testid="recalibrations-paper-label">
              PAPER TRADING
            </span>
            This page reads <span className="num">GET /risk/recalibrations</span> and renders what it
            answered. Nothing here loosens a limit, signs a proposal, proposes one or submits an
            order: a proposal is generated by the platform&rsquo;s LEARN stage from regret it scored
            itself and can be supplied by nobody, a signature is{" "}
            <span className="num">POST /risk/recalibrations/{"{rule}"}/approvals</span> and needs an
            operator, and the gateway declares no write this page could call.
          </p>
        </PanelBody>
      </Panel>

      <Panel>
        <PanelHead title="Proposals standing open" meta={<Freshness resource={recalibrations} name="open proposals" />} />
        <PanelBody>
          <ResourceView resource={recalibrations} loadingRows={4}>
            {(data) => (
              <>
                <KpiRow>
                  <Kpi
                    label="Limit set in force"
                    value={<span data-testid="recalibrations-limits">{data.limits}</span>}
                    note="GET /risk/recalibrations: limits — the file a signed artefact would replace"
                  />
                  <Kpi
                    label="Open"
                    value={<span data-testid="recalibrations-open-count">{formatCount(data.open.length)}</span>}
                    note="proposals a signature can land on; nothing else can be signed"
                    tone={data.open.length > 0 ? "warn" : "neutral"}
                  />
                  <Kpi
                    label="Records in the log"
                    value={
                      <span data-testid="recalibrations-history-count">{formatCount(data.history.length)}</span>
                    }
                    note="every proposal ever written — proposed, withdrawn and enacted — bounded by retention"
                  />
                </KpiRow>

                {data.open.length === 0 ? (
                  <div className="mt-3" data-testid="recalibrations-open-empty">
                    <EmptyBlock headline="No recalibration is standing open.">
                      <p>
                        Observed, not unread: the route answered and its{" "}
                        <code className="num">open</code> list is empty. A proposal appears when the
                        LEARN stage has scored enough refusals by one rule to say that rule refused
                        too much; no rule has cleared that bar in this process, and no bound is
                        awaiting anybody&rsquo;s signature.
                      </p>
                    </EmptyBlock>
                  </div>
                ) : (
                  <div className="mt-3 flex flex-col gap-2" data-testid="recalibrations-open-list">
                    {data.open.map((proposal) => (
                      <ProposalCard key={`open:${proposal.rule}:${proposal.at}`} proposal={proposal} />
                    ))}
                  </div>
                )}
              </>
            )}
          </ResourceView>
        </PanelBody>
      </Panel>

      <Panel>
        <PanelHead title="Every proposal the log holds" meta={<Freshness resource={recalibrations} name="proposal history" />} />
        <PanelBody flush>
          <ResourceView resource={recalibrations} loadingRows={5}>
            {(data) =>
              data.history.length === 0 ? (
                <div className="p-3" data-testid="recalibrations-history-empty">
                  <EmptyBlock headline="The log holds no proposal record.">
                    <p>
                      The platform has never proposed a change to one of its own bounds in this
                      process&rsquo;s log. That is an answer, not a gap.
                    </p>
                  </EmptyBlock>
                </div>
              ) : (
                <TableWell maxHeight="520px" label="every recalibration proposal the log holds, oldest first">
                  <table className="dt" data-testid="recalibrations-history-table">
                    <thead>
                      <tr>
                        <th scope="col">Rule</th>
                        <th scope="col">Kind</th>
                        <th scope="col">Outcome</th>
                        <th scope="col" className="n">
                          Current bound
                        </th>
                        <th scope="col" className="n">
                          Proposed bound
                        </th>
                        <th scope="col" className="n">
                          Regret
                        </th>
                        <th scope="col">Recorded</th>
                      </tr>
                    </thead>
                    <tbody>
                      {data.history.map((proposal, index) => (
                        <tr
                          key={`history:${proposal.rule}:${proposal.outcome}:${proposal.at}:${index}`}
                          data-testid="recalibrations-history-row"
                          data-outcome={proposal.outcome}
                        >
                          <th scope="row" className="num">
                            {proposal.rule}
                          </th>
                          <td>{proposal.kind}</td>
                          <td>
                            <OutcomeChip outcome={proposal.outcome} />
                          </td>
                          <td className="n num">{formatBound(proposal.current_bound)}</td>
                          <td className="n num">{formatBound(proposal.proposed_bound)}</td>
                          <td className="n num">
                            {formatCount(proposal.evidence.regrets)}/{formatCount(proposal.evidence.sample)}
                          </td>
                          <td className="num">{formatTimestamp(proposal.at)}</td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </TableWell>
              )
            }
          </ResourceView>
        </PanelBody>
      </Panel>
    </div>
  );
}

/**
 * One open proposal, whole: the bound, the evidence that argued for it, and
 * the sentence the platform wrote about it.
 *
 * The rationale is shown verbatim. It is generated from the evidence by the
 * platform and no caller can supply it, so paraphrasing it here would replace
 * the record with this console's summary of the record.
 */
function ProposalCard({ proposal }: { proposal: RecalibrationProposal }) {
  const evidence = proposal.evidence;
  return (
    <article
      className="border border-[color:var(--color-line)] bg-[color:var(--color-surface)] p-3"
      data-testid="recalibrations-open-proposal"
      data-rule={proposal.rule}
    >
      <header className="flex flex-wrap items-center gap-2">
        <span className="num text-[13px] font-semibold text-[color:var(--color-ink)]">{proposal.rule}</span>
        <Chip>{proposal.kind}</Chip>
        <OutcomeChip outcome={proposal.outcome} />
        <span className="num ml-auto text-[11px] text-[color:var(--color-ink-faint)]">
          {formatTimestamp(proposal.at)}
        </span>
      </header>

      <div className="mt-2 flex flex-wrap items-baseline gap-x-2 gap-y-1 text-[12px]">
        <span className="text-[color:var(--color-ink-dim)]">bound</span>
        <span className="num text-[color:var(--color-ink)]" data-testid="recalibrations-current-bound">
          {formatBound(proposal.current_bound)}
        </span>
        <span aria-hidden="true" className="text-[color:var(--color-ink-faint)]">
          &rarr;
        </span>
        <span className="num text-[color:var(--color-ink)]" data-testid="recalibrations-proposed-bound">
          {formatBound(proposal.proposed_bound)}
        </span>
        <span className="text-[11px] text-[color:var(--color-ink-faint)]">
          both as the platform sent them; this page does not difference them
        </span>
      </div>

      <p
        className="mt-2 max-w-[90ch] text-[12px] leading-relaxed text-[color:var(--color-ink-dim)]"
        data-testid="recalibrations-rationale"
      >
        {proposal.rationale}
      </p>

      <dl className="mt-2 grid grid-cols-2 gap-x-4 gap-y-1 text-[11.5px] sm:grid-cols-4">
        <Fact label="Scored refusals" value={formatCount(evidence.sample)} />
        <Fact label="Regretted" value={formatCount(evidence.regrets)} />
        <Fact
          label="Regret fraction"
          value={formatPercent(evidence.regret_fraction)}
          note="the platform's figure; not recomputed here"
        />
        <Fact
          label="Would have earned"
          value={
            <span data-testid="recalibrations-would-have-earned">
              {formatDecimal(evidence.would_have_earned.simulated_value)}{" "}
              {evidence.would_have_earned.simulated ? (
                <Chip tone="warn" title="qip_twin::Simulated: a world that did not happen">
                  SIMULATED
                </Chip>
              ) : null}
            </span>
          }
          note="what standing aside cost, in a world that did not happen"
        />
      </dl>

      <p className="mt-2 text-[11px] leading-relaxed text-[color:var(--color-ink-faint)]">
        Evidence window <span className="num">{formatTimestamp(evidence.window[0])}</span> to{" "}
        <span className="num">{formatTimestamp(evidence.window[1])}</span>, newest scored order{" "}
        <span className="num" data-testid="recalibrations-newest-order">
          {truncate(evidence.newest, 30)}
        </span>{" "}
        of {formatCount(evidence.scored_orders.length)} in the sample.
      </p>
    </article>
  );
}

function Fact({ label, value, note }: { label: string; value: React.ReactNode; note?: string }) {
  return (
    <div className="min-w-0">
      <dt className="eyebrow truncate">{label}</dt>
      <dd className="num text-[13px] text-[color:var(--color-ink)]">{value}</dd>
      {note ? <p className="text-[10.5px] leading-snug text-[color:var(--color-ink-faint)]">{note}</p> : null}
    </div>
  );
}

/**
 * The outcome, with the one thing a reader must not infer from the word.
 *
 * `enacted` means two people signed and an artefact was emitted for a
 * deployment to commit — not that this process is running the new bound. The
 * title says so wherever the chip appears, because the chip is the only place
 * a reader skimming the history table meets the word at all.
 */
function OutcomeChip({ outcome }: { outcome: string }) {
  const tone = outcome === PROPOSAL_ENACTED ? "info" : outcome === PROPOSAL_WITHDRAWN ? "neutral" : "warn";
  const title =
    outcome === PROPOSAL_ENACTED
      ? "two signatures emitted a limit set with this bound replaced, as an artefact for a deployment to commit and mount; this process keeps the limits it booted with"
      : outcome === PROPOSAL_WITHDRAWN
        ? "the evidence stopped clearing the bar before anybody signed"
        : outcome === PROPOSAL_PROPOSED
          ? "standing open; a first signature is held and a second, from a different person, emits the artefact"
          : "an outcome this console does not recognise, rendered as the platform sent it";
  return (
    <Chip tone={tone} title={title}>
      <span data-testid="recalibrations-outcome">{outcome}</span>
    </Chip>
  );
}
