//! Data provenance, quality and licensing.
//!
//! Section 21 of the charter is blunt: bad data must never silently become an
//! investment decision. Every record therefore carries where it came from, when
//! it was true, when it arrived, and how much of it survived validation. The
//! opportunity and reasoning stages refuse to act on records below a quality
//! floor, and licensing class governs whether a record may leave the platform.

use qip_core::Timestamp;
use serde::{Deserialize, Serialize};

/// How a dataset may be used and redistributed.
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize, Default)]
#[serde(rename_all = "snake_case")]
pub enum LicensingClass {
    /// Freely redistributable.
    Public,
    /// Usable internally; may not be redistributed.
    #[default]
    Internal,
    /// Licensed from a vendor with per-seat or per-use terms.
    Licensed,
    /// Licensed and non-displayable — derived values only may be shown.
    Restricted,
    /// Generated by the platform. Never valid in production decisions.
    Synthetic,
}

impl LicensingClass {
    /// Whether raw values may be shown in the UI or returned by the API.
    pub fn allows_raw_display(&self) -> bool {
        matches!(self, Self::Public | Self::Internal | Self::Synthetic)
    }

    /// Whether the class is admissible for a real capital decision.
    pub fn allows_production_decisions(&self) -> bool {
        !matches!(self, Self::Synthetic)
    }
}

/// Where a record came from and when.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Provenance {
    /// Adapter or vendor that produced the record, e.g. `synthetic-exchange`.
    pub source: String,
    /// When the fact was true in the world.
    pub event_time: Timestamp,
    /// When the platform learned it. Never earlier than `event_time` for a
    /// well-behaved feed; a violation is recorded as a quality issue.
    pub ingestion_time: Timestamp,
    /// Upstream record identity, for reconciliation against the vendor.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub upstream_id: Option<String>,
    pub licensing: LicensingClass,
    /// Ids of the records this one was derived from.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub derived_from: Vec<String>,
}

impl Provenance {
    pub fn new(
        source: impl Into<String>,
        event_time: Timestamp,
        ingestion_time: Timestamp,
    ) -> Self {
        Self {
            source: source.into(),
            event_time,
            ingestion_time,
            upstream_id: None,
            licensing: LicensingClass::Internal,
            derived_from: Vec::new(),
        }
    }

    pub fn synthetic(source: impl Into<String>, at: Timestamp) -> Self {
        Self {
            source: source.into(),
            event_time: at,
            ingestion_time: at,
            upstream_id: None,
            licensing: LicensingClass::Synthetic,
            derived_from: Vec::new(),
        }
    }

    pub fn with_licensing(mut self, licensing: LicensingClass) -> Self {
        self.licensing = licensing;
        self
    }

    pub fn with_upstream_id(mut self, id: impl Into<String>) -> Self {
        self.upstream_id = Some(id.into());
        self
    }

    pub fn derived(mut self, parents: Vec<String>) -> Self {
        self.derived_from = parents;
        self
    }

    /// Delay between the fact and the platform learning it.
    pub fn ingestion_latency(&self) -> qip_core::Duration {
        self.ingestion_time.since(self.event_time)
    }

    /// How stale the record is as of `now`.
    pub fn age_at(&self, now: Timestamp) -> qip_core::Duration {
        now.since(self.event_time)
    }
}

/// Quality assessment attached to a record or dataset.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DataQuality {
    /// Fraction of expected fields that are present, in `[0, 1]`.
    pub completeness: f64,
    /// Confidence the value is correct, in `[0, 1]`.
    pub confidence: f64,
    /// Number of validation rules that failed.
    pub validation_failures: u32,
    /// Human-readable descriptions of what failed.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub issues: Vec<String>,
    /// True when the value was interpolated or carried forward rather than
    /// observed. Point-in-time correctness depends on tracking this.
    pub is_imputed: bool,
}

impl Default for DataQuality {
    fn default() -> Self {
        Self {
            completeness: 1.0,
            confidence: 1.0,
            validation_failures: 0,
            issues: Vec::new(),
            is_imputed: false,
        }
    }
}

impl DataQuality {
    /// A record that passed every check.
    pub fn clean() -> Self {
        Self::default()
    }

    /// Record a failed validation rule, lowering confidence.
    pub fn with_issue(mut self, issue: impl Into<String>) -> Self {
        self.issues.push(issue.into());
        self.validation_failures += 1;
        // Each additional failure halves the remaining confidence rather than
        // subtracting a fixed amount, so confidence approaches zero without
        // ever going negative.
        self.confidence *= 0.5;
        self
    }

    pub fn imputed(mut self) -> Self {
        self.is_imputed = true;
        self.confidence *= 0.8;
        self
    }

    /// Single score combining completeness and confidence.
    pub fn score(&self) -> f64 {
        (self.completeness.clamp(0.0, 1.0) * self.confidence.clamp(0.0, 1.0)).clamp(0.0, 1.0)
    }

    /// Whether the record clears a quality floor.
    pub fn meets(&self, floor: f64) -> bool {
        self.score() >= floor
    }

    /// Combine with another assessment, taking the worse of each dimension.
    ///
    /// A derived value is never better quality than its worst input.
    pub fn combined_with(&self, other: &Self) -> Self {
        let mut issues = self.issues.clone();
        issues.extend(other.issues.iter().cloned());
        Self {
            completeness: self.completeness.min(other.completeness),
            confidence: self.confidence.min(other.confidence),
            validation_failures: self.validation_failures + other.validation_failures,
            issues,
            is_imputed: self.is_imputed || other.is_imputed,
        }
    }
}

/// The quality floor below which a record may not drive a decision.
pub const DECISION_QUALITY_FLOOR: f64 = 0.6;
