# Development: the central plane on its own, on Cloud Run.
#
# Still no execution node, and the reason has changed. This header used to say
# "a node exists to be next to a venue, and there is no venue here". That
# reason no longer holds: ADR 0035 authorises exactly one node — `newyork-1`,
# `us-east4`, shadow mode, this environment and no other — and the node it
# authorises prices from `QIP_VENUE_FEED=simulated`, the in-process matching
# engine, so it needs no venue's published address ranges at all. Leaving the
# stale reason in place would tell the next reader the node is unauthorised
# when what it actually is, is unbuildable.
#
# What blocks it is named beside the commented entry below: no boot image
# exists yet, and nobody has chosen the node's capital allocation. The first
# of those changed shape rather than going away. `.github/workflows/image.yml`
# and `infrastructure/images/execution-node/` are now the bake — built from
# the container image `deploy.yml` attested, refusing to run on an artefact
# the attestor did not sign — but it has never been dispatched, so no image
# self-link exists to write here. Producing one is three human acts, and the
# order matters because the obvious one is wrong: uncomment
# `image_bake_subnet_cidr` below, dispatch `infra.yml` with `action=up` (which
# is what creates the staging bucket, the builder identity and the /28), and
# only then dispatch `image.yml`. A bake dispatched first refuses, naming this
# file. The allocation is not like that at all: it is a number a person
# chooses and no workflow may pick, and ADR 0045 proposes one without setting
# it. So `execution_nodes = {}` stays — a working configuration, not an
# incomplete one. `docs/operations/deploying-an-edge-cell.md` carries the whole
# sequence, both values included, under "The exact sequence".

# The project this environment lives in. An identifier, not a secret: it
# appears in every resource name and in the pipeline's own configuration, so
# keeping it out of version control would buy nothing and cost reproducibility.
#
# Each environment names a project of its own, or says it has none. Two
# environments in one project share one IAM boundary, one KMS key ring and one
# Binary Authorization attestor, whatever their name prefixes say.
project_id = "algorik-dev"

# The project's numeric id, recorded so nothing has to ask for it. It is an
# identifier like the id above, Google's service agents are named by it, and
# the workload-identity audience contains it — a workflow that can read this
# file can construct its own authentication with no repository variable
# involved, which matters because a variable set from a broken shell once
# carried an install advisory where this number should have been.
project_number = 95200532413

environment      = "dev"
region           = "us-east4"
autonomy_ceiling = "paper_trading"

# --- The trust zones (blueprint §46.1) ---------------------------------------
#
# The three zones the catalogue places a workload in, and no others: a zone
# with nothing in it constrains nothing, and a range chosen for a zone nobody
# uses is the range that collides later. Each is a /24 — a Cloud Run direct
# VPC egress interface needs a /26 or larger and Google reserves addresses
# in it as instances scale.
#
# The ranges sit above the console's 10.0.16.0/26 and below the ladder the
# execution nodes draw from (10.<64+n>.0.0/16, per environments/README.md),
# so nothing here overlaps a node's range whichever node is added first.
trust_zones = {
  "application-identity" = {
    region      = "us-east4"
    subnet_cidr = "10.0.32.0/24"
  }
  "cognition" = {
    region      = "us-east4"
    subnet_cidr = "10.0.33.0/24"
  }
  "intelligence" = {
    region      = "us-east4"
    subnet_cidr = "10.0.34.0/24"
  }
  # Declared for OpenObserve (ADR 0028 decision 5), which is the only
  # workload in this zone and reaches nothing: it receives OTLP from the
  # API's drain and serves an operator who holds a binding. No entry in
  # `permitted_paths`, `external_egress` or `public_ingress` names it, so
  # the zone is default-deny in both directions like every other, and the
  # zone existing is not the same as anything being able to reach it.
  "management" = {
    region      = "us-east4"
    subnet_cidr = "10.0.35.0/24"
  }
}

# No path between zones, no external egress declared here, no public
# ingress. The API is reached by the console as a named Cloud Run invoker,
# which needs no firewall path; nothing here reaches a vendor, because no
# vendor's ranges have been recorded and the proxy's IBM listeners are
# reachable from no zone declared here. Each of these is a declaration
# somebody has to write down, with a note saying why. The one external
# destination this environment does reach — GitHub, from the management
# zone, for the control plane below — is generated by the root from
# `gitops_enabled` rather than typed here, so it exists exactly when the
# reconcilers that need it do.
permitted_paths = {}
external_egress = {}
public_ingress  = {}

# --- The GitOps control plane (ADR 0036) --------------------------------------
#
# The one environment with a control plane today: an Autopilot cluster in
# the `management` zone above running Config Connector, Argo CD and Kargo,
# reconciling infrastructure/gitops/envs/dev/ into this project. The three
# services `deploy.yml` last moved here — the digests images.tfvars used to
# record — are the digests envs/dev names, so Config Connector's first
# reconcile acquires each service and changes nothing; that is the evidence
# the ADR asks for and `docs/ops/missing-infrastructure-register.md` will
# record. The endpoint's /28 sits above the management zone's /24 and below
# the execution nodes' ladder (10.65.0.0/16 upward), overlapping neither.
#
# **The cluster is suspended (ADR 0093) and this flag is deliberately still
# `true`, which is the opposite of what that record first said.** Every
# published Argo CD image fails `vendor.yml`'s blocking CRITICAL gate on
# CVE-2025-68121 in its bundled `kustomize` and `git-lfs`, and no release on
# any line fixes it, so the cluster cannot install the controllers that are
# its whole purpose while a regional Autopilot control plane bills whether or
# not a Pod runs. The suspension is real; the mechanism is `infra.yml`'s
# `suspend` action, not this flag.
#
# Closing the flag was tried first and refused at plan time, by a guard that
# is right: `module.gitops_control_plane`'s `count` goes to zero with it, and
# that plans a destroy of `google_kms_crypto_key.etcd`, which declares
# `prevent_destroy` because "destroying the key makes every Secret in etcd
# unreadable at once, and the failure appears on the next control-plane
# restart rather than now". Run 54 aborted on exactly that
# (<https://github.com/droderiquesit/quantum-ai-platform/actions/runs/35531628713>).
# The guard cannot express "unless the cluster is going too", and it is not
# weakened to make this convenient.
#
# So the key and everything else in the module stay in state, and `suspend`
# destroys the one resource that bills. The cost of that shape is stated
# where it belongs, in ADR 0093: a later plain `up` recreates the cluster,
# because the configuration still says there should be one. The durable fix
# is to move the etcd key out of the gated module so this flag *can* close;
# that is a `moved` block and a module interface change, and it is named in
# the record rather than done in a hurry against live state.
gitops_enabled                = true
gitops_master_ipv4_cidr_block = "10.0.36.0/28"

# --- The one node ADR 0035 authorises, and the two values it still lacks -----
#
# ADR 0035 decides: one execution node, `us-east4`, shadow mode, `dev`. Every
# field below is determined and reviewable; the two written as `<...>` are the
# ones nobody in this repository can honestly supply, and they are why the map
# below this comment is still empty rather than why the decision is open.
#
#   * `newyork-1` is the ladder's third block (environments/README.md) and
#     `modules/connectivity/NOT-ORDERED.md` records it as the `us-east4` cell:
#     Ashburn, about 300km from the NY/NJ venues. Node id and cell id are one
#     name — the binary reads it as QIP_CELL_ID and refuses an envelope
#     addressed elsewhere.
#   * `10.67.0.0/20` is that block. It overlaps neither the trust zones
#     (10.0.32-35.0/24), nor the console (10.0.16.0/26), nor the control
#     plane's endpoint (10.0.36.0/28).
#   * `c3-highcpu-8` is the smallest shape §41.4 permits, which is the right
#     one for a node configured for a single venue. Note what it costs: the
#     module derives `isolcpus=2-7`, and §41.3's thread assignment wants
#     2-15. modules/execution-node/README.md says so and the module exports
#     `isolated_cpus` so a deployment can see which of the two it got.
#   * The venue is the in-process matching engine. `startup.sh.tftpl` writes
#     `QIP_VENUE_FEED=simulated`, which is the only value the binary accepts,
#     and it sets no QIP_VENUE_ADAPTER, so `VenueChoice` builds the simulator.
#     `venues` cannot be empty — the module's precondition and the binary both
#     refuse that — so the entry names the simulated venue and gives it a
#     range from RFC 5737's documentation block, which routes nowhere by
#     definition. That is the honest address for a venue that is in the
#     process: not a real venue's range, and not guessed to be one. Shadow
#     mode creates no rule from it in any case.
#   * `create_egress_nat = false`. `modules/network` creates no NAT anywhere
#     and this node needs none: it reaches Google APIs over the restricted VIP
#     through private Google access and the central plane over the VPC, and a
#     NAT would give it an IP-layer route to the internet that nothing asked
#     for.
#   * `boot_image` has no value anyone can write **yet**. There is now a bake
#     — `.github/workflows/image.yml`, with `infrastructure/images/
#     execution-node/` — which turns the container image `deploy.yml` attested,
#     the vendored Envoy and a pinned Ops Agent into a Compute Engine image
#     meeting the startup script's checks (isolcpus, huge pages, no swap, no
#     container runtime, /usr/local/bin/{qip-edge-node,envoy,qip-fetch-secret},
#     the Ops Agent). It has never been dispatched, so there is no self-link.
#     The image is built for one machine shape — the isolated-core range is in
#     its kernel command line — so the image named here and `machine_type`
#     above have to be the same shape or the node boots and declines to trade.
#     Writing a plausible self-link here would still produce a plan that reads
#     as ready and an apply that fails after the subnet, the identity and four
#     IAM bindings exist.
#   * `region_allocation` is the ceiling on the capital this cell may hold in
#     reservation. It has no default anywhere on purpose: a default is a number
#     nobody chose, and this is the one number in a cell's envelope a reviewer
#     has to have read. An agent picking it would be exactly that failure.
#     A number is now *proposed* — ADR 0045, `"1000000"`, one tenth of
#     `PlatformConfig::initial_equity`, with its derivation, the alternatives
#     it rejects and the concentration failure it is the last defence against.
#     Proposed is not chosen: that record says so in its own first paragraph
#     and states that this map stays `{}` until somebody edits this file in a
#     reviewed diff. Reading the ADR is the act; writing the number here is a
#     second one, and it is a person's.
#
# execution_nodes = {
#   "newyork-1" = {
#     region       = "us-east4"
#     zone         = "us-east4-a"
#     subnet_cidr  = "10.67.0.0/20"
#     machine_type = "c3-highcpu-8"
#     boot_image   = "projects/algorik-dev/global/images/<the baked image>"
#     venues = {
#       "simulated-1" = { cidr = "192.0.2.0/24", port = 443 }
#     }
#     create_egress_nat = false
#     region_allocation = "<the ceiling a person chose>"
#     default_pricing    = ""
#     strategy_plan_path = ""
#     # §31.1. Empty is every venue in the node's own region, which is the only
#     # state any node has run in. A path here declares which venues are abroad
#     # and the band this region mirrors each instrument under; it cannot widen
#     # what the node trades, and the binary refuses at start-up a declaration
#     # naming a venue outside `venues` above.
#     cross_region_mirror_path = ""
#   }
# }
#
# Shadow mode is not here and must not be added: `main.tf` passes
# `shadow_mode = true` as a literal, so no tfvars value can let a node out of
# it, and `an_execution_node_may_reach_its_venues_and_the_central_plane_and_
# nothing_else` in the acceptance suite refuses the change.
execution_nodes = {}

# --- Where the node's boot image is baked ------------------------------------
#
# Commented out, so `module.image_bake` creates nothing and this plan is
# unchanged by its existence. Uncommenting it and applying creates three
# things: a staging bucket, an identity whose only grant is reading that
# bucket, and a /28 with no route to the internet for the throwaway machine
# `.github/workflows/image.yml` builds the image on. None of them is an
# execution node and none of them bills while idle beyond a few objects the
# bucket's lifecycle rule expires after a week.
#
# `10.0.37.0/28` is free: it sits above the control plane's endpoint range
# (10.0.36.0/28) and the trust zones (10.0.32-35.0/24), above the console
# (10.0.16.0/26), and far below the ladder the execution nodes draw from
# (10.<64+n>.0.0/16, per environments/README.md) — so it overlaps nothing
# here and nothing a node would take.
#
# This is the first of the two acts ADR 0035 is waiting on. The second —
# `region_allocation` — is a number a person chooses and nothing may default.
#
# image_bake_subnet_cidr = "10.0.37.0/28"

# Every managed service off. Development runs on memory, which is what the
# implemented storage targets are for on an instance with no volume.
enable_bigquery      = false
enable_cloud_storage = false
enable_alloydb       = false
enable_bigtable      = false
enable_memorystore   = false
enable_spanner       = false
enable_vertex_ai     = false

# --- Off, and each is a decision rather than an oversight --------------------

# Security Command Center's project-scoped resources. Off because they only
# ever evaluate if SCC is activated at the organisation, which is not a
# project-level act and which nothing here can check. Detectors that are
# stored and never run read in the console as a project being watched, which
# is worse than the gap they replace.
enable_security_command_center = false

# The only repository whose pipeline may deploy into this project. No default
# exists for this on purpose: a default would name a repository somebody else
# could be running, and the consequence of getting it wrong is that their
# pipeline pushes images and moves services here.
github_repository = "droderiquesit/quantum-ai-platform"

# Flip to true and re-apply only once a scrape has been observed — a
# `prometheus.googleapis.com/qip_*` descriptor visible in this project. The
# alert policies name Prometheus metrics, and Cloud Monitoring refuses a
# policy for a metric it has never ingested. While this is false the alerts
# do not exist, which is the honest description of an environment nothing
# has scraped: modules/observability/NOT-SCRAPED.md says what does not yet.
# workload_metrics_exist = true
#
# The collector that would produce that descriptor is declared in
# modules/cloudrun and attached to both brains by catalogue.tf, but only once
# a digest is named here — one vendor.yml has mirrored and attested from a
# reviewed line in infrastructure/egress/vendored-images.txt.
#
# That review has now happened and its answer was no. vendor.yml run 11
# mirrored Google's collector 1.9.2 and Trivy failed it on CVE-2026-56854, a
# CRITICAL authentication bypass in golang.org/x/crypto v0.54.0, fixed in
# 0.55.0 and unfixed in every version the registry publishes — 1.9.2 is the
# newest tag it has. So this stays unset because the only available image
# fails the platform's own scan gate, not because nobody looked. The full
# finding is in vendored-images.txt beside the commented line.
# metrics_collector_image_digest = "sha256:<the mirrored collector's digest>"

# OpenObserve (ADR 0028): the platform's metrics, logs and traces backend,
# mirrored to infrastructure/egress/vendored-images.txt as `vendor/openobserve`
# but not deployed anywhere until this names the digest. Unlike the metrics
# collector, setting this creates a whole new top-level Cloud Run service
# (catalogue.tf's `module.openobserve`), not a sidecar on an existing one —
# and that service also needs a `management` entry in `trust_zones` above,
# which this environment now declares.
#
# The digest is the one `vendored-images.txt` reviewed and vendor.yml run
# 33789488338 mirrored into this environment's registry and attested, so
# Binary Authorization admits it. Confirmed independently before it was set
# here: `crane digest docker.io/openobserve/openobserve:v0.92.2` answers this
# same sha256, so the tag had not moved under the reviewed line.
vendored_openobserve_image_digest = "sha256:88fb692ac791d3eaff69653a4a4686f1c7eceb9e105491d58d29ac2739560b3b"

# --- The six optional files the central roots can be given, and why none
# --- is named here ---
#
# `venue_registrations_file`, `wallet_statement_file` and
# `capital_fabric_file` stay at their default
# of null, so `catalogue.tf` renders no configuration file for either and the
# API sees neither QIP_VENUE_REGISTRATIONS_PATH nor QIP_WALLET_STATEMENT_PATH.
# `central_horizons_file` and `source_candidates_file` — the deep brain's own
# pair, following the same convention — stay null for the same reason, argued
# below, and so does `risk_limits_file`, the one file all three roots share.
# Absent is a state each variable documents, not an omission:
#
# venue_registrations_file = "data/registrations/venue-registrations.json"
#   would mount the records the API's registry ships with. Nobody has
#   registered with a venue from this environment, and a record is a named
#   person's act — they read the terms, registered under their own identity
#   and wrote the credential into its Secret Manager slot before the file
#   could honestly exist (docs/operations/registering-a-venue.md). Unset, the
#   shipped registry holds nobody and every source needing an account is
#   refused, which is what a deployment where nobody registered should do.
#
# wallet_statement_file = "data/statements/<the day's statement>.json"
#   would mount a custodian's dated statement for LEARN to reconcile the
#   wallet against. This environment trades on the in-process simulated venue
#   (ADR 0003), which issues no statement, and no custodian relationship
#   exists for the paper book — so there is nothing to mount. It is also a
#   same-day act: the kernel holds a statement fresh for one day and the API
#   refuses a stale one at start-up, so a file committed today is a refused
#   start tomorrow. Unset, the banner says there is no feed and /wallet
#   answers `assembled: false`, which is the truthful answer for a process
#   nothing has reported to.
#
# capital_fabric_file = "data/fabric/<the desk's declaration>.json"
#   would mount the destinations, corridors and transfer intents §37 and §38
#   are about — the only production route by which any of them reaches the
#   chain, and the reason /transfer-gate answered `last_assessment: null`
#   permanently rather than transiently before the mount existed. This desk
#   holds no external destination: it trades the paper book on the in-process
#   simulated venue (ADR 0003), and there is nowhere a corridor could carry
#   capital to. Declaring one anyway would put an act on the hash-chained log
#   that nobody performed, and the log is not a place to write a rehearsal.
#
#   It is also append-only in a way the other two are not. Every command in
#   it is journalled the first time the API applies it, and from then on
#   editing or removing that command refuses the start and refuses the cycle:
#   a sealed record is not rewritten, so a correction is another act — a
#   revoke, a suspend — appended after it.
#
#   What it cannot do, whatever it says: move money. ADR 0021 permits the
#   deterministic gate and refuses the engine behind it, an admitted verdict
#   carries no way to execute, and no code in this workspace consumes one.
#
# central_horizons_file = "data/horizons/<the desk's §23.4 policy>.json"
#   would mount how the whole-book risk budget divides across the four
#   blueprint horizons and which horizon each strategy sits at, arming
#   `CentralPlane::arm_horizons` — the gate that stays unarmed without one.
#   No strategy run from this environment has been given a stated horizon, so
#   there is no claim to declare; setting this without one would arm a gate
#   against a policy nobody actually holds.
#
# risk_limits_file = "data/risk-limits/<the desk's signed set>.json"
#   would mount the limit set every central root boots on, in place of the
#   shipped `conservative_default`. It is the only path by which a bound
#   reaches a running process (ADR 0061): the LEARN stage proposes a
#   loosening from counterfactual regret, two operators sign it through the
#   API, and the second signature emits this file — the running set with one
#   bound replaced — for a person to commit and name here. No recalibration
#   has been signed, so there is no artefact to mount, and the shipped set is
#   the one every process has ever run under. A file named here may move a
#   bound and nothing else: `LimitSet::validate` refuses one that drops a
#   control, and refuses one that keeps every shipped name but changes what
#   a name measures — its kind, its axis, its confidence, whether it forces
#   a reduction — under that name. A moved bound is admitted and named in
#   the boot banner as "differs from shipped in: <name> bound".
#
# source_candidates_file = "data/datasets/source-candidates.json"
#   would mount the candidate data sources the deep brain's discovery desk
#   assesses on its cadence (blueprint §7.4-§7.6.2) — the one production
#   caller `DataFinder::assess` has, and with it the licensing evaluation, the
#   dark-tier hard line, the robots check and the schema fingerprint that ran
#   only in tests before it.
#
#   It is the *second* step and not the first. Every entry names the egress
#   route its source is reached through, and under ADR 0060 a source is probed
#   only where a reviewed route already exists — an Envoy cluster and a
#   listener in egress/envoy.yaml, because the proxy is a reverse proxy and a
#   process cannot name a destination in a request that has no field for one.
#   The committed catalogue names `api.frankfurter.dev` on 127.0.0.1:9105,
#   which this environment's bootstrap does serve; it stays unset because
#   nothing has yet been observed making that call from a deployed process,
#   and mounting it would put a claim in the banner that no run has earned.
#
#   Unset, the deep brain assesses nothing and its banner says so. That is not
#   a degraded state: no control reads the source catalogue, so an absent one
#   starves nothing — unlike an absent universe, which feeds no exposure
#   bucket and leaves two limits unable to fire, and is refused at start-up
#   for exactly that reason.
#
# deepbrain_connector = { sources = ["frankfurter-ecb-reference-rates"], base_url = "http://127.0.0.1:9105" }
#   would have the deep brain poll the named catalogued connectors beside its
#   own stream (QIP_CONNECTOR_SOURCE, QIP_CONNECTOR_BASE_URL), through the
#   egress sidecar it carries — the one brain that can reach a vendor (ADR
#   0024) — with every fetch digested and referenced on its ledger. Left
#   null: the proxy has never been applied, the one FX host its bootstrap
#   names answered a 301 from the host the manifest named until that was
#   corrected, and no subject has two vendors among the shipped connectors
#   anyway, so a value today would start polling a vendor for a rule-31 hold
#   it cannot lift. Setting it is the reviewed step that turns a deployment's
#   reference ledger from replays-only to a vendor's own bytes.
#
# deepbrain_discover_every = "<a whole number of cycles, or explicitly "0">"
#   would turn on the source-discovery pass on its own cadence
#   (QIP_DEEPBRAIN_DISCOVER_EVERY). Left null, the desk keeps its own default
#   of zero — no pass — which matches the fact that `source_candidates_file`
#   above is also null: a cadence with nothing to assess would run and decide
#   about nothing, so the pair is turned on together or not at all.
#
# region_dark_after = "<a whole number of seconds, e.g. 300>"
#   would have the API derive a region dark once every cell in it has been
#   silent that long (QIP_REGION_DARK_AFTER, ADR 0079): nothing new is
#   granted into a dark region, its share is frozen at its last lit value,
#   its last book is held in the aggregate rather than dropped, and every
#   mirror into it suspends. Left null, the derivation is off and
#   /api/v1/regions answers `"region_dark_after": null` — "nobody is looking",
#   said out loud rather than read as "no region is dark". Null here for two
#   reasons. This API serves no mesh (QIP_MESH_CELLS is unset: a Cloud Run
#   service publishes one port), so a window would arm a derivation over a
#   centre that can hear no cell, and the route would render the window as
#   though somebody were. And no measurement exists yet to pick the number
#   from — too short refuses healthy regions their grants, too long delays
#   the refusal past the point it protects anything. Set it beside the mesh,
#   when the fabric exists; the API refuses zero, a fraction and anything
#   above the twelve-hour envelope ceiling at start-up, naming this variable.

# --- Customer identity ------------------------------------------------------
# Identity Platform for customer sign-in, activated once real hostnames
# existed to authorize. The domains are the Cloud Run URLs a deploy actually
# printed (never invented, per the variable's contract) plus localhost for
# development against the real project.
enable_identity_platform = true
identity_authorized_domains = [
  "localhost",
  "algorik-portal-rgxpsss2lq-uk.a.run.app",
  "algorik-landing-rgxpsss2lq-uk.a.run.app",
]

# --- The console's route to the platform (ADR 0018) --------------------------
#
# The portal reaches `qip-api` at the API's own Cloud Run URL, as the one
# invoker the catalogue names. This subnet is the interface the portal's
# direct VPC egress attaches to; 10.0.16.0/26 is a /26 because that is the
# smallest direct VPC egress accepts, and the console needs a handful of
# addresses, not a network.
#
# There is no `api_internal_address` any more. The GKE runtime reserved an
# address for an internal load balancer the cluster created from a Service;
# with no cluster there is no load balancer and nothing to reserve. The URL
# the console calls is the `api_internal_base_url` output.
console_egress_cidr = "10.0.16.0/26"

# --- The public edge (blueprint §40.5, §40.14) --------------------------------
#
# Absent, and absent is a decision. `modules/public-edge` declares Cloud Armor,
# the global HTTPS load balancer and Cloud CDN, and creates none of them while
# `hostnames` is empty — which it is here and in every other environment.
#
# There is no customer surface deployed to put behind one. `frontend/landing`
# and `frontend/portal` exist in the tree and are in no catalogue, no image
# matrix and no manifest; an edge standing in front of nothing would be a
# public address on the internet answering 404, from a certificate Google
# would refuse to issue until somebody pointed DNS at it.
#
# Turning it on is three decisions, in this order: a name the desk owns, a DNS
# record pointing it at the `public_edge` output's address, and — if the
# authenticated APIs are to be reachable at all — a backend naming a Cloud Run
# service in `application-identity`. The module refuses any other zone at plan
# time, so trading traffic cannot end up behind the same load balancer by an
# edit to this file.
#
#   public_edge = {
#     hostnames = ["console.example.com"]
#     application_backend = {
#       service_name = "qip-dev-api"
#       trust_zone   = "application-identity"
#     }
#     rate_limit_requests_per_minute = 600
#     permitted_regions              = []
#   }

# --- The GitOps control plane's public front door ----------------------------
#
# ADR 0036 built this cluster with a private endpoint and no public address,
# and this section is the deliberate, environment-scoped widening of that.
# What becomes reachable is two controller UIs; the API server, the nodes and
# the endpoint are untouched and stay private.
#
# The order of the gates is the design. A request hits a Google load
# balancer, terminates TLS on a Google-managed certificate, and is then
# handed to Identity-Aware Proxy, which checks the caller against
# `roles/iap.httpsResourceAccessor` **before** anything reaches the cluster.
# An unauthenticated request is refused by Google's front end and never
# becomes a packet on the VPC, so Argo CD's login page is not an
# internet-facing surface.
#
# Behind IAP there is still a password, and the redundancy is deliberate:
# IAP decides who may reach the service, Argo CD decides who may act on it.
# A misconfigured IAP policy still meets a credential; a leaked credential
# still meets IAP. One gate in front of a controller that can reconcile
# arbitrary manifests into this cluster is one gate too few.
gitops_gateway_enabled = false
gitops_argocd_hostname = ""
gitops_kargo_hostname  = ""

# **Off, and the reason is that there is no Google-provided hostname for a
# GKE Gateway and the owner is not buying a domain.**
#
# Everything above stays true about what this door *would* be; what changed is
# that it cannot be opened without a name somebody owns and delegates. Argo CD
# and Kargo run in the cluster. A Cloud Run service gets a `run.app` hostname
# and a Google-managed certificate for free; a GKE Gateway gets an IP address
# and nothing else — Google publishes no DNS name for one, and a managed
# certificate is issued for a domain or not at all. There is no third option,
# and the two commonly reached for are worse than the gap: a third-party
# wildcard resolver puts a control plane's hostname in somebody else's DNS,
# and a self-signed certificate trains an operator to click through a warning
# in front of the one console that can reconcile arbitrary manifests into this
# cluster.
#
# So these two are reached the way the private cluster was already designed to
# be reached, and the way `infra.yml` itself reaches it — the fleet's Connect
# gateway, then a port-forward:
#
#   gcloud container fleet memberships get-credentials qip-dev-gitops \
#     --project algorik-dev
#   kubectl -n argocd port-forward svc/argocd-server 8080:443
#   kubectl -n kargo  port-forward svc/kargo-api     8081:443
#
# That publishes nothing at all: no address, no certificate, no listener, and
# no surface on the internet for anybody to find. For a controller with this
# much authority that is the better answer rather than the cheaper one, and
# `infrastructure/gitops/README.md` is where it is written down for an
# operator who is not reading tfvars.
#
# Turning it back on is two hostnames and this flag, and needs a domain first.
# The root refuses the half-configuration — the flag true with either name
# empty — rather than letting the module fail on a DNS regex that says nothing
# about the decision that was got wrong.

# --- The console's front door: the URL Google already issued it ----------------
#
# ADR 0095, narrowing ADR 0094. **Empty is not "no console door" — it is the
# door Cloud Run gives every service for nothing.**
#
# Cloud Run enforces Identity-Aware Proxy on the service itself, across every
# ingress path, including the default `run.app` URL. Google's page says it in
# one sentence: "By enabling IAP on Cloud Run directly, you can secure traffic
# with a single click from all ingress paths, including default run.app URLs
# and load balancers." So the console is reachable at
#
#   https://qip-dev-portal-95200532413.us-east4.run.app
#
# on a Google-managed certificate, behind IAP, with no address reserved, no
# certificate ordered, no Cloud Armor policy, no zone, no registrar and no
# nameserver to delegate. `terraform output console_front_door` prints it,
# along with the one command that admits a person to it.
#
# **Two doors, never both.** Setting this name selects `module.portal_edge`
# instead — the load balancer of ADR 0094 — and Google refuses the pair
# outright: "You cannot configure IAP on both the load balancer and the Cloud
# Run service." The two modules' `count` expressions are exact negations.
#
# Two things settle it for dev rather than merely favouring it. The managed
# certificate on the other door stays in PROVISIONING until somebody creates
# an A record at a registrar, which is the requirement this change exists to
# remove. And `infra.yml` run 71 failed applying that door's Cloud Armor
# policy with `Quota 'SECURITY_POLICY_RULES' exceeded. Limit: 0.0 globally` —
# **zero**, not exceeded-by-one: the project has no Cloud Armor allowance at
# all, a backend service is the only thing Cloud Armor attaches to, and
# raising it is a quota request that may not be granted. With this door the
# policy, the backend, the load balancer, the address and the certificate go
# away together, and the rest of the environment applies.
#
# **What is lost, named rather than dropped quietly.** The other door carried
# a Cloud Armor rate limit that banned an admitted session behaving like a
# script. This door has none: IAP still decides who may pass, and nothing
# bounds how fast an admitted caller may go. That control was never applied —
# the quota refused it on the one run that tried — so nothing is being turned
# off, but it is a refusal this environment does not have and should not be
# assumed to.
#
# Who may pass is a **per-service** list now, which ADR 0094 could not have:
# a Gateway's backend service has no Terraform address, so its grant had to be
# project-level and admitted a person to Argo CD, Kargo and the console at
# once. IAP on Cloud Run is addressable per service, so the console's list is
# the people who may read the console. It is empty and stays empty; see below.
#
# What stands behind IAP is the portal's own session check
# (`ALGORIK_AUTH_REQUIRED=true`), for the same reason Argo CD keeps its
# password: IAP decides who may reach the service, the service decides who may
# act on it, and one gate in front of a console that reads the platform's book
# is one gate too few.
gitops_portal_hostname = ""

# **Empty, and seeded out of band — like every credential in this tree.**
#
# An IAM member is an account identifier, and this repository does not carry
# those: `.claude/rules/00-enterprise-governance.md` refuses a token, key or
# account identifier in code, and a committed `user:someone@example.com` is
# exactly that. It would also be the one line of this configuration that has
# to change whenever a person joins or leaves, in a file reviewed by commit.
#
# So a front door is applied admitting nobody, which is a posture rather
# than a failure, and an operator is granted by name afterwards.
#
# **This list is read only by `module.gitops_gateway`, which is off, so today
# it grants nothing anywhere.** It is kept at `[]` rather than deleted because
# the variable is what the gateway's access list would be on the day somebody
# buys a domain and turns that door back on.
#
# The console's list is not this one and is not project-level. IAP on Cloud
# Run is addressable per service, so the command that admits a person to the
# portal names the portal:
#
#   gcloud iap web add-iam-policy-binding \
#     --project=algorik-dev --resource-type=cloud-run \
#     --region=us-east4 --service=qip-dev-portal \
#     --role=roles/iap.httpsResourceAccessor \
#     --member='user:YOU@example.com'
#
# `terraform output console_front_door` prints that command filled in.
# `--resource-type=cloud-run` is the part that is easy to lose: the same
# subcommand without it edits the **project's** IAP policy, which is the wide
# grant ADR 0095 narrowed away from.
#
# Until somebody runs it, the URL resolves and IAP refuses every caller. That
# is the correct state for a console whose readers have not been named yet.
gitops_iap_members = []

# --- The domain: not owned, and no longer needed -------------------------------
#
# **Empty, because nothing in this environment has a name to resolve any
# more.** `module.dns_zone`'s `count` is on this value, so an empty string
# creates no zone, no records and nothing for a registrar to point at.
#
# The zone existed to answer three names — `argocd`, `kargo` and `portal` —
# and each of those is gone or reached another way. The portal is at its
# Google-issued `run.app` URL behind Cloud Run's own IAP; Argo CD and Kargo
# are reached through the fleet's Connect gateway and a port-forward. A zone
# with no records in it is a billed resource and a nameserver delegation
# somebody still has to perform, in exchange for nothing.
#
# **What this removes is the whole reason the delegation existed.** Setting
# `dns_zone_domain` created the zone but did *not* make the domain resolve
# from it: the registrar still named its own nameservers until somebody
# replaced them with `terraform output dns_zone`'s four, by hand, in a web
# form. Every front door in this tree sat complete and serving nothing while
# that step was outstanding, because a Google-managed certificate stays in
# PROVISIONING until its name resolves. No door here now waits on it.
#
# The module is kept and so is the variable. The day a vanity hostname is
# wanted, this is the file that turns it on, and the constraint below still
# holds when it does: **exactly one environment may set this**, because a
# domain has one authoritative zone, two environments creating one each would
# both apply cleanly and serve two different sets of records from two
# different sets of nameservers, and no plan can catch it — each environment
# has its own state and none can see another's.
# `a_single_environment_owns_the_dns_zone_for_the_domain` in the
# infrastructure acceptance suite is what catches it, by reading all four
# tfvars.
dns_zone_domain = ""

# Five minutes, chosen rather than inherited. A TTL is a promise about how long
# a mistake lasts, and these names have never resolved, so the first thing that
# happens to each is somebody getting it wrong. It also bounds the wait on the
# only feedback there is: a certificate leaves PROVISIONING once its name
# resolves, and a record cached for a day is a certificate that does not issue
# for a day. What a low TTL costs is query volume on three names three people
# type, which is not a reason. Raise it when the addresses have been stable for
# a while.
dns_record_ttl_seconds = 300
