# Development: the central plane on its own, on Cloud Run.
#
# Still no execution node, and the reason has changed. This header used to say
# "a node exists to be next to a venue, and there is no venue here". That
# reason no longer holds: ADR 0035 authorises exactly one node — `newyork-1`,
# `us-east4`, shadow mode, this environment and no other — and the node it
# authorises prices from `QIP_VENUE_FEED=simulated`, the in-process matching
# engine, so it needs no venue's published address ranges at all. Leaving the
# stale reason in place would tell the next reader the node is unauthorised
# when what it actually is, is unbuildable.
#
# What blocks it is named beside the commented entry below: no boot image
# exists yet, and nobody has chosen the node's capital allocation. The first
# of those changed shape rather than going away. `.github/workflows/image.yml`
# and `infrastructure/images/execution-node/` are now the bake — built from
# the container image `deploy.yml` attested, refusing to run on an artefact
# the attestor did not sign — but it has never been dispatched, so no image
# self-link exists to write here. Producing one is three human acts, and the
# order matters because the obvious one is wrong: uncomment
# `image_bake_subnet_cidr` below, dispatch `infra.yml` with `action=up` (which
# is what creates the staging bucket, the builder identity and the /28), and
# only then dispatch `image.yml`. A bake dispatched first refuses, naming this
# file. The allocation is not like that at all: it is a number a person
# chooses and no workflow may pick, and ADR 0045 proposes one without setting
# it. So `execution_nodes = {}` stays — a working configuration, not an
# incomplete one. `docs/operations/deploying-an-edge-cell.md` carries the whole
# sequence, both values included, under "The exact sequence".

# The project this environment lives in. An identifier, not a secret: it
# appears in every resource name and in the pipeline's own configuration, so
# keeping it out of version control would buy nothing and cost reproducibility.
#
# Each environment names a project of its own, or says it has none. Two
# environments in one project share one IAM boundary, one KMS key ring and one
# Binary Authorization attestor, whatever their name prefixes say.
project_id = "algorik-dev"

# The project's numeric id, recorded so nothing has to ask for it. It is an
# identifier like the id above, Google's service agents are named by it, and
# the workload-identity audience contains it — a workflow that can read this
# file can construct its own authentication with no repository variable
# involved, which matters because a variable set from a broken shell once
# carried an install advisory where this number should have been.
project_number = 95200532413

environment      = "dev"
region           = "us-east4"
autonomy_ceiling = "paper_trading"

# --- The trust zones (blueprint §46.1) ---------------------------------------
#
# The three zones the catalogue places a workload in, and no others: a zone
# with nothing in it constrains nothing, and a range chosen for a zone nobody
# uses is the range that collides later. Each is a /24 — a Cloud Run direct
# VPC egress interface needs a /26 or larger and Google reserves addresses
# in it as instances scale.
#
# The ranges sit above the console's 10.0.16.0/26 and below the ladder the
# execution nodes draw from (10.<64+n>.0.0/16, per environments/README.md),
# so nothing here overlaps a node's range whichever node is added first.
trust_zones = {
  "application-identity" = {
    region      = "us-east4"
    subnet_cidr = "10.0.32.0/24"
  }
  "cognition" = {
    region      = "us-east4"
    subnet_cidr = "10.0.33.0/24"
  }
  "intelligence" = {
    region      = "us-east4"
    subnet_cidr = "10.0.34.0/24"
  }
  # Declared for OpenObserve (ADR 0028 decision 5), which is the only
  # workload in this zone and reaches nothing: it receives OTLP from the
  # API's drain and serves an operator who holds a binding. No entry in
  # `permitted_paths`, `external_egress` or `public_ingress` names it, so
  # the zone is default-deny in both directions like every other, and the
  # zone existing is not the same as anything being able to reach it.
  "management" = {
    region      = "us-east4"
    subnet_cidr = "10.0.35.0/24"
  }
}

# No path between zones, no external egress declared here, no public
# ingress. The API is reached by the console as a named Cloud Run invoker,
# which needs no firewall path; nothing here reaches a vendor, because no
# vendor's ranges have been recorded and the proxy's IBM listeners are
# reachable from no zone declared here. Each of these is a declaration
# somebody has to write down, with a note saying why. The one external
# destination this environment does reach — GitHub, from the management
# zone, for the control plane below — is generated by the root from
# `gitops_enabled` rather than typed here, so it exists exactly when the
# reconcilers that need it do.
permitted_paths = {}
external_egress = {}
public_ingress  = {}

# --- The GitOps control plane (ADR 0036) --------------------------------------
#
# The one environment with a control plane today: an Autopilot cluster in
# the `management` zone above running Config Connector, Argo CD and Kargo,
# reconciling infrastructure/gitops/envs/dev/ into this project. The three
# services `deploy.yml` last moved here — the digests images.tfvars used to
# record — are the digests envs/dev names, so Config Connector's first
# reconcile acquires each service and changes nothing; that is the evidence
# the ADR asks for and `docs/ops/missing-infrastructure-register.md` will
# record. The endpoint's /28 sits above the management zone's /24 and below
# the execution nodes' ladder (10.65.0.0/16 upward), overlapping neither.
gitops_enabled                = true
gitops_master_ipv4_cidr_block = "10.0.36.0/28"

# --- The one node ADR 0035 authorises, and the two values it still lacks -----
#
# ADR 0035 decides: one execution node, `us-east4`, shadow mode, `dev`. Every
# field below is determined and reviewable; the two written as `<...>` are the
# ones nobody in this repository can honestly supply, and they are why the map
# below this comment is still empty rather than why the decision is open.
#
#   * `newyork-1` is the ladder's third block (environments/README.md) and
#     `modules/connectivity/NOT-ORDERED.md` records it as the `us-east4` cell:
#     Ashburn, about 300km from the NY/NJ venues. Node id and cell id are one
#     name — the binary reads it as QIP_CELL_ID and refuses an envelope
#     addressed elsewhere.
#   * `10.67.0.0/20` is that block. It overlaps neither the trust zones
#     (10.0.32-35.0/24), nor the console (10.0.16.0/26), nor the control
#     plane's endpoint (10.0.36.0/28).
#   * `c3-highcpu-8` is the smallest shape §41.4 permits, which is the right
#     one for a node configured for a single venue. Note what it costs: the
#     module derives `isolcpus=2-7`, and §41.3's thread assignment wants
#     2-15. modules/execution-node/README.md says so and the module exports
#     `isolated_cpus` so a deployment can see which of the two it got.
#   * The venue is the in-process matching engine. `startup.sh.tftpl` writes
#     `QIP_VENUE_FEED=simulated`, which is the only value the binary accepts,
#     and it sets no QIP_VENUE_ADAPTER, so `VenueChoice` builds the simulator.
#     `venues` cannot be empty — the module's precondition and the binary both
#     refuse that — so the entry names the simulated venue and gives it a
#     range from RFC 5737's documentation block, which routes nowhere by
#     definition. That is the honest address for a venue that is in the
#     process: not a real venue's range, and not guessed to be one. Shadow
#     mode creates no rule from it in any case.
#   * `create_egress_nat = false`. `modules/network` creates no NAT anywhere
#     and this node needs none: it reaches Google APIs over the restricted VIP
#     through private Google access and the central plane over the VPC, and a
#     NAT would give it an IP-layer route to the internet that nothing asked
#     for.
#   * `boot_image` has no value anyone can write **yet**. There is now a bake
#     — `.github/workflows/image.yml`, with `infrastructure/images/
#     execution-node/` — which turns the container image `deploy.yml` attested,
#     the vendored Envoy and a pinned Ops Agent into a Compute Engine image
#     meeting the startup script's checks (isolcpus, huge pages, no swap, no
#     container runtime, /usr/local/bin/{qip-edge-node,envoy,qip-fetch-secret},
#     the Ops Agent). It has never been dispatched, so there is no self-link.
#     The image is built for one machine shape — the isolated-core range is in
#     its kernel command line — so the image named here and `machine_type`
#     above have to be the same shape or the node boots and declines to trade.
#     Writing a plausible self-link here would still produce a plan that reads
#     as ready and an apply that fails after the subnet, the identity and four
#     IAM bindings exist.
#   * `region_allocation` is the ceiling on the capital this cell may hold in
#     reservation. It has no default anywhere on purpose: a default is a number
#     nobody chose, and this is the one number in a cell's envelope a reviewer
#     has to have read. An agent picking it would be exactly that failure.
#     A number is now *proposed* — ADR 0045, `"1000000"`, one tenth of
#     `PlatformConfig::initial_equity`, with its derivation, the alternatives
#     it rejects and the concentration failure it is the last defence against.
#     Proposed is not chosen: that record says so in its own first paragraph
#     and states that this map stays `{}` until somebody edits this file in a
#     reviewed diff. Reading the ADR is the act; writing the number here is a
#     second one, and it is a person's.
#
# execution_nodes = {
#   "newyork-1" = {
#     region       = "us-east4"
#     zone         = "us-east4-a"
#     subnet_cidr  = "10.67.0.0/20"
#     machine_type = "c3-highcpu-8"
#     boot_image   = "projects/algorik-dev/global/images/<the baked image>"
#     venues = {
#       "simulated-1" = { cidr = "192.0.2.0/24", port = 443 }
#     }
#     create_egress_nat = false
#     region_allocation = "<the ceiling a person chose>"
#     default_pricing    = ""
#     strategy_plan_path = ""
#   }
# }
#
# Shadow mode is not here and must not be added: `main.tf` passes
# `shadow_mode = true` as a literal, so no tfvars value can let a node out of
# it, and `an_execution_node_may_reach_its_venues_and_the_central_plane_and_
# nothing_else` in the acceptance suite refuses the change.
execution_nodes = {}

# --- Where the node's boot image is baked ------------------------------------
#
# Commented out, so `module.image_bake` creates nothing and this plan is
# unchanged by its existence. Uncommenting it and applying creates three
# things: a staging bucket, an identity whose only grant is reading that
# bucket, and a /28 with no route to the internet for the throwaway machine
# `.github/workflows/image.yml` builds the image on. None of them is an
# execution node and none of them bills while idle beyond a few objects the
# bucket's lifecycle rule expires after a week.
#
# `10.0.37.0/28` is free: it sits above the control plane's endpoint range
# (10.0.36.0/28) and the trust zones (10.0.32-35.0/24), above the console
# (10.0.16.0/26), and far below the ladder the execution nodes draw from
# (10.<64+n>.0.0/16, per environments/README.md) — so it overlaps nothing
# here and nothing a node would take.
#
# This is the first of the two acts ADR 0035 is waiting on. The second —
# `region_allocation` — is a number a person chooses and nothing may default.
#
# image_bake_subnet_cidr = "10.0.37.0/28"

# Every managed service off. Development runs on memory, which is what the
# implemented storage targets are for on an instance with no volume.
enable_bigquery      = false
enable_cloud_storage = false
enable_alloydb       = false
enable_bigtable      = false
enable_memorystore   = false
enable_spanner       = false
enable_vertex_ai     = false

# --- Off, and each is a decision rather than an oversight --------------------

# Security Command Center's project-scoped resources. Off because they only
# ever evaluate if SCC is activated at the organisation, which is not a
# project-level act and which nothing here can check. Detectors that are
# stored and never run read in the console as a project being watched, which
# is worse than the gap they replace.
enable_security_command_center = false

# The only repository whose pipeline may deploy into this project. No default
# exists for this on purpose: a default would name a repository somebody else
# could be running, and the consequence of getting it wrong is that their
# pipeline pushes images and moves services here.
github_repository = "droderiquesit/quantum-ai-platform"

# Flip to true and re-apply only once a scrape has been observed — a
# `prometheus.googleapis.com/qip_*` descriptor visible in this project. The
# alert policies name Prometheus metrics, and Cloud Monitoring refuses a
# policy for a metric it has never ingested. While this is false the alerts
# do not exist, which is the honest description of an environment nothing
# has scraped: modules/observability/NOT-SCRAPED.md says what does not yet.
# workload_metrics_exist = true
#
# The collector that would produce that descriptor is declared in
# modules/cloudrun and attached to both brains by catalogue.tf, but only once
# a digest is named here — one vendor.yml has mirrored and attested from a
# reviewed line in infrastructure/egress/vendored-images.txt.
#
# That review has now happened and its answer was no. vendor.yml run 11
# mirrored Google's collector 1.9.2 and Trivy failed it on CVE-2026-56854, a
# CRITICAL authentication bypass in golang.org/x/crypto v0.54.0, fixed in
# 0.55.0 and unfixed in every version the registry publishes — 1.9.2 is the
# newest tag it has. So this stays unset because the only available image
# fails the platform's own scan gate, not because nobody looked. The full
# finding is in vendored-images.txt beside the commented line.
# metrics_collector_image_digest = "sha256:<the mirrored collector's digest>"

# OpenObserve (ADR 0028): the platform's metrics, logs and traces backend,
# mirrored to infrastructure/egress/vendored-images.txt as `vendor/openobserve`
# but not deployed anywhere until this names the digest. Unlike the metrics
# collector, setting this creates a whole new top-level Cloud Run service
# (catalogue.tf's `module.openobserve`), not a sidecar on an existing one —
# and that service also needs a `management` entry in `trust_zones` above,
# which this environment now declares.
#
# The digest is the one `vendored-images.txt` reviewed and vendor.yml run
# 33789488338 mirrored into this environment's registry and attested, so
# Binary Authorization admits it. Confirmed independently before it was set
# here: `crane digest docker.io/openobserve/openobserve:v0.92.2` answers this
# same sha256, so the tag had not moved under the reviewed line.
vendored_openobserve_image_digest = "sha256:88fb692ac791d3eaff69653a4a4686f1c7eceb9e105491d58d29ac2739560b3b"

# --- The three optional files the API is given, and why none is named here ---
#
# `venue_registrations_file`, `wallet_statement_file` and
# `capital_fabric_file` stay at their default
# of null, so `catalogue.tf` renders no configuration file for either and the
# API sees neither QIP_VENUE_REGISTRATIONS_PATH nor QIP_WALLET_STATEMENT_PATH.
# Absent is a state each variable documents, not an omission:
#
# venue_registrations_file = "data/registrations/venue-registrations.json"
#   would mount the records the API's registry ships with. Nobody has
#   registered with a venue from this environment, and a record is a named
#   person's act — they read the terms, registered under their own identity
#   and wrote the credential into its Secret Manager slot before the file
#   could honestly exist (docs/operations/registering-a-venue.md). Unset, the
#   shipped registry holds nobody and every source needing an account is
#   refused, which is what a deployment where nobody registered should do.
#
# wallet_statement_file = "data/statements/<the day's statement>.json"
#   would mount a custodian's dated statement for LEARN to reconcile the
#   wallet against. This environment trades on the in-process simulated venue
#   (ADR 0003), which issues no statement, and no custodian relationship
#   exists for the paper book — so there is nothing to mount. It is also a
#   same-day act: the kernel holds a statement fresh for one day and the API
#   refuses a stale one at start-up, so a file committed today is a refused
#   start tomorrow. Unset, the banner says there is no feed and /wallet
#   answers `assembled: false`, which is the truthful answer for a process
#   nothing has reported to.
#
# capital_fabric_file = "data/fabric/<the desk's declaration>.json"
#   would mount the destinations, corridors and transfer intents §37 and §38
#   are about — the only production route by which any of them reaches the
#   chain, and the reason /transfer-gate answered `last_assessment: null`
#   permanently rather than transiently before the mount existed. This desk
#   holds no external destination: it trades the paper book on the in-process
#   simulated venue (ADR 0003), and there is nowhere a corridor could carry
#   capital to. Declaring one anyway would put an act on the hash-chained log
#   that nobody performed, and the log is not a place to write a rehearsal.
#
#   It is also append-only in a way the other two are not. Every command in
#   it is journalled the first time the API applies it, and from then on
#   editing or removing that command refuses the start and refuses the cycle:
#   a sealed record is not rewritten, so a correction is another act — a
#   revoke, a suspend — appended after it.
#
#   What it cannot do, whatever it says: move money. ADR 0021 permits the
#   deterministic gate and refuses the engine behind it, an admitted verdict
#   carries no way to execute, and no code in this workspace consumes one.

# --- Customer identity ------------------------------------------------------
# Identity Platform for customer sign-in, activated once real hostnames
# existed to authorize. The domains are the Cloud Run URLs a deploy actually
# printed (never invented, per the variable's contract) plus localhost for
# development against the real project.
enable_identity_platform = true
identity_authorized_domains = [
  "localhost",
  "algorik-portal-rgxpsss2lq-uk.a.run.app",
  "algorik-landing-rgxpsss2lq-uk.a.run.app",
]

# --- The console's route to the platform (ADR 0018) --------------------------
#
# The portal reaches `qip-api` at the API's own Cloud Run URL, as the one
# invoker the catalogue names. This subnet is the interface the portal's
# direct VPC egress attaches to; 10.0.16.0/26 is a /26 because that is the
# smallest direct VPC egress accepts, and the console needs a handful of
# addresses, not a network.
#
# There is no `api_internal_address` any more. The GKE runtime reserved an
# address for an internal load balancer the cluster created from a Service;
# with no cluster there is no load balancer and nothing to reserve. The URL
# the console calls is the `api_internal_base_url` output.
console_egress_cidr = "10.0.16.0/26"
